EdgeApp/edge-currency-accountbased

- src/stellar/stellarPlugin.js
- src/xrp/xrpPlugin.js
- test/plugin/fixtures.json
- test/xrp/fixtures.json
* XRP: parse for dt= not tag=
* XLM: parse for memo= and if memo_type is present, make sure it is MEMO_ID
> Fix parseUri of unique identifier

- src/eos/eosEngine.js
- src/stellar/stellarEngine.js
- src/xrp/xrpEngine.js
Check for undefined totalBalances[currencyCode] and throw InsufficientFundsError
> Fix incorrect error on insufficient funds

- .gitignore
- package.json
- rollup.config.test.js
- src/common/engine.js
- src/common/export-fixes.js
- src/common/utils.js
- src/eos/eosEngine.js
- src/eos/eosPlugin.js
- src/ethereum/ethEngine.js
- src/ethereum/ethInfo.js
- src/ethereum/ethMiningFees.js
- src/ethereum/ethPlugin.js
- src/ethereum/ethSchema.js
- src/ethereum/ethTypes.js
- src/index.js
- src/stellar/stellarEngine.js
- src/xrp/xrpEngine.js
- test/engine/engine.js
- test/engine/fixtures.json
- test/plugin/fixtures.json
- test/plugin/plugin.js
- webpack.config.js
- yarn.lock
This is built on top of PR https://github.com/EdgeApp/edge-currency-accountbased/pull/8 which adds EOS functionality. Merge that PR first.
> Add Ethereum

- src/ethereum/ethInfo.js
@kylanhurt Please feel free to edit & force-push as needed to get it right.
> Add the HERC token

- src/ethereum/ethEngine.js
* Add Infura to broadcast APIs
* Change logic to broadcast to all APIs via promiseAny
* Remove code to handle incrementing/decrementing nonce
> Refactor broadcastTx

- src/ethereum/ethEngine.js
Use higher parameters returned from ethGasStation for determining suggested fees.
> Cheat fees upward for ethereum txs

- src/xrp/xrpEngine.js
Make sure fee is included in nativeAmount for outgoing transactions.
> Fix tx amount for XRP

- src/eos/eosEngine.js
Set walletLocalDataDirty true to make sure name is saved
> Properly save account name when detected

- src/ethereum/ethPlugin.js
The purpose of this task is to add a method for Ethereum that allows a private seed to be imported (and then passed to create a new wallet from the private key).
Asana Task: https://app.asana.com/0/361770107085503/854351955485162/f
> Implement improtePrivateKey on Ethereum

- package.json
- src/common/plugin.js
- src/common/utils.js
- src/ethereum/ethPlugin.js
- yarn.lock
The purpose of this task is to get the Ethereum plugin to properly determine denomination info for customTokens, specifically when working with encoded and parsed URI's.
Asana Task: https://app.asana.com/0/361770107085503/1118536468069439/f
> Fix Issue with Token Denominations for QR Code Parsing and Encoding

- src/ethereum/ethPlugin.js
Asana Task: https://app.asana.com/0/361770107085503/1120660944635608/f
> Clean privateKey for ETH import

- .travis.yml
Trying some stuff to get Travis builds working again.
> Use yarn instead of npm for travis builds

- src/common/utils.js
- src/eos/eosEngine.js
- src/eos/eosInfo.js
- src/eos/eosSchema.js
- src/eos/eosTypes.js
Asana Tasks:
https://app.asana.com/0/361770107085503/1126446211249634/f
https://app.asana.com/0/361770107085503/1126627318452253/f
> Fix EOS Incoming Transaction Issue

- src/common/engine.js
- src/eos/eosEngine.js
- src/eos/eosTypes.js
Asana Task: https://app.asana.com/0/361770107085503/1128525148171844/f
> Get EOS Incoming & Outgoing Transactions Working

- src/ethereum/ethEngine.js
* Prevent empty strings to be a valid eth / token balance.
> Prevent empty strings to be a valid eth / token balance

- package.json
- src/common/utils.js
- src/eos/eosInfo.js
- src/ethereum/ethInfo.js
- src/index.js
- src/stellar/stellarInfo.js
- src/tezos/tezosEngine.js
- src/tezos/tezosInfo.js
- src/tezos/tezosPlugin.js
- src/tezos/tezosSchema.js
- src/tezos/tezosTypes.js
- src/xrp/xrpInfo.js
- test/tezos/engine.test.js
- webpack.config.js
- yarn.lock
Refactor imageServerUrl amongs plugins
Add eztz to yarn.lock
Supsersedes https://github.com/EdgeApp/edge-currency-accountbased/pull/48
> Integration of Tezos

- src/binance/bnbEngine.js
> Remove signedTx from transaction object

- src/rsk/rskPlugin.js
Implement import key and mnemonic (RSK)
Remove unnecessary comments
> Implement import key and mnemonic for RSK

- package.json
- src/common/engine.js
- src/eos/eosEngine.js
- src/eos/eosInfo.js
- src/eos/eosPlugin.js
- src/react-native-io.js
- yarn.lock
> Directly connect to EOS producers (with multicast)

- src/tezos/tezosInfo.js
After the latest update, tzscan may not always be up to date.
> Use Tezos mystique server

- src/ethereum/ethEngine.js
- src/ethereum/ethNetwork.js
[x] The console log in ETH network line 534 needs to be updated since it is no longer referencing the correct function name
[x] It looks like you still have the function check transactions fetch in the engine but it is no longer used
[x] The function fetch get should probably get moved to the network file even though it is still used in the engine
[x] You also added eight new functions to the block of code which binds this. I don’t believe any of that was needed since you never passed the function as an argument to another function.
[x] Also. Did you verify that the balance that you are setting in the response is in the smallest unit of Ethereum. And that it is a string?
[] Another comment. It looks like you’re checking Etherscan before Bloq chair for the token balance. That should be …
> Address Pauls comments from my prior PR

- src/rsk/rskEngine.js
Module `proxy` is no longer available.
> Updates RSK engine to the changed Blockscout API

- src/fio/fioInfo.js
Add mainnet APIs
Update addressExplorer and transactionExplorer to mainnet
> Update icon URL to Edge server

- src/fio/fioEngine.js
- src/fio/fioPlugin.js
I believe this should give us credit for any FIO registrations that happen in the app.
> Pass a TPID to the FIO SDK

- package.json
- src/common/engine.js
- src/common/schema.js
- yarn.lock
JSON-schema does not result in usable error messages in cases like this. The new cleaners v0.2.0 has more information in its error messages.
> Use cleaners to check basic Edge types

- src/fio/fioConst.js
- src/fio/fioEngine.js
- src/fio/fioInfo.js
- src/fio/fioPlugin.js
- src/fio/fioSchema.js
* Loop from newest to latest.
* Break the loop if node returns error.
> Fio check transactions algo changes.

- src/ethereum/ethInfo.js
> Add AAVE tokens

- src/eos/eosEngine.js
- src/eos/eosInfo.js
- src/eos/eosPlugin.js
- src/eos/eosSchema.js
Also add additional error handling regarding account activation.
> Fix hyperian node endpoint

- src/ethereum/ethInfo.js
- src/ethereum/ethNetwork.js
Also log result object when checkTokenBalEthscan throws an error
> Fix contractAddress variable name

- src/binance/bnbEngine.js
> Uncomment BNB's resync function

- package.json
- src/ethereum/ethPlugin.js
- test/plugin/fixtures.js
- test/plugin/plugin.test.js
- yarn.lock
A checksum is present if any of the letters in the address are upper-case. This also removes unnecessary ethereum-checksum-address module and uses ethereumjs-util instead
> Throw error if there is a checksum present and it fails verification

- package.json
- src/xrp/xrpPlugin.js
- test/xrp/fixtures.js
- test/xrp/plugin.test.js
- yarn.lock
Replaces https://github.com/EdgeApp/edge-currency-accountbased/pull/306
> XRP x address support

- package.json
- src/ethereum/ethEngine.js
- src/ethereum/ethInfo.js
- src/ethereum/ethNetwork.js
- src/ethereum/ethSchema.js
- src/ethereum/ethTypes.js
- yarn.lock
- Add support for Ropsten network integrations for some service providers
- Add base-fee-multiplier fee algorithm
> EIP-1559: Base Fee Multiplier Fee Algorithm

- src/common/engine.js
- src/common/types.js
- src/fio/fioConst.js
- src/fio/fioEngine.js
- src/fio/fioInfo.js
Added logic to fetch fio requests in engine and provide them in otherMethods.
> Get fio requests loop

- src/common/engine.js
- src/common/types.js
- src/fio/fioEngine.js
- src/fio/fioPlugin.js
The new otherLocalData cache wasn't initialized correctly and was causing issues when accessing it's values. walletLocalData already works so we should use that instead.
> Remove new otherLocalData cache and use existing walletLocalData cache

- src/fio/fioEngine.js
fetchFioRequests was always passing two different arrays to fioRequestsListChanged which was guaranteed to return true. Therefore the number of requests would go back and forth between two values causing inconsistent behavior in the gui. This simplification compares the previously saved array directly to the one queried from the blockchain and saves if it actually changed.
This change in logic means we don't need to pay attention to any in-progress (selected and in the process of paying) requests in fioRequestsToApprove. Since querying the blockchain will always be slightly behind user actions in the gui we can remove those requests from the gui (separate PR) once it's successfully paid instead of removing them from the plugin payload.
> Simplify FIO request fetching

- src/common/utils.js
- src/ethereum/ethEngine.js
- src/ethereum/ethTypes.js
Also timeConnected in payload to GUI
> Add hack to add fee info to transaction methods

- src/zcash/zecEngine.js
- Remove otherParams in makeSpend
- Remove resync boolean from 
- Fix getDisplayPublicSeed
> ZEC style fixes 

- .gitignore
- src/ethereum/ethEngine.js
- src/ethereum/ethNetwork.js
- src/ethereum/ethSchema.js
- src/ethereum/ethTypes.js
- src/ethereum/maticInfo.js
- src/index.js
Add support for Polygon (mainnet)
---
- https://app.asana.com/0/0/1201079877863004
- https://app.asana.com/0/0/1201533915611272
> Add support for Polygon (mainnet)

- package.json
- src/binance/bnbInfo.js
- src/eos/eosInfo.js
- src/eos/telosInfo.js
- src/eos/waxInfo.js
- src/hedera/hederaInfo.js
- src/stellar/stellarInfo.js
- src/xrp/xrpInfo.js
- test/engine/engine.test.js
- yarn.lock
Upgrade edge-core-js to v0.18.13
> Add memo maxLength

- src/ethereum/ethNetwork.js
---
- https://app.asana.com/0/0/1201587268984283
> Add support for array of polygon api keys

- src/common/plugin.js
- test/plugin/fixtures.js
- test/plugin/plugin.test.js
---
- https://app.asana.com/0/0/1201617140921564
> Add support for RenBridge Gateway address uri

- package.json
- src/fio/fioConst.js
- src/fio/fioEngine.js
- yarn.lock
Replacing https://github.com/EdgeApp/edge-currency-accountbased/pull/347
> Append add bundled transactions case to fioAction

- src/zcash/zecEngine.js
---
- https://app.asana.com/0/0/1201660234465298
> Prevent spending if wallet isn't synced

- package.json
- src/common/engine.js
- src/eos/eosEngine.js
- src/ethereum/ethEngine.js
- src/fio/fioEngine.js
- src/hedera/hederaEngine.js
- src/xrp/xrpEngine.js
- src/zcash/zecEngine.js
- yarn.lock
---
- https://app.asana.com/0/0/1201411731543803
> Add Zcash max spend

- package.json
- src/fio/fioConst.js
- src/fio/fioEngine.js
- src/fio/fioInfo.js
- src/fio/fioPlugin.js
- src/fio/fioSchema.js
- test/engine/engine.test.js
- test/eos/activation.test.js
- test/tezos/engine.test.js
- yarn.lock
Replaces https://github.com/EdgeApp/edge-currency-accountbased/pull/313
FIOSDK version need to be updated
---
- https://app.asana.com/0/0/1200692419869086
- https://app.asana.com/0/0/1200759268116595
> FIO Staking

- src/fio/fioEngine.js
1. Use the `unlockDate` to search for placement of a transaction in the
`stakingStatus`.
2. Insert new elements into `stakedAmounts` in order by the
`unlockDate`.
---
- https://app.asana.com/0/0/1201738645894993
- https://app.asana.com/0/0/1201732235071085
> Fix `unlockDate` issues for FIO's `stakingStatus`

- .flowconfig
- package.json
- src/index.js
- src/solana/solanaEngine.js
- src/solana/solanaInfo.js
- src/solana/solanaPlugin.js
- src/solana/solanaTypes.js
- yarn.lock
---
- https://app.asana.com/0/0/1201425242712354
> Add Solana

- src/fio/fioEngine.js
This is a reasonable abstraction so we can re-use this calculation
in `updateStakingStatus` and `makeSpend`.
> Abstract unlockDate calculation into a `getUnlockDate` method

- package.json
- src/fio/fioEngine.js
- src/solana/solanaEngine.js
- src/solana/solanaInfo.js
- src/solana/solanaPlugin.js
- src/solana/solanaTypes.js
- yarn.lock
- Derive keys according to industry standard path
- Update explorer links
- Prevent adding empty string as memo
---
- https://app.asana.com/0/0/1201794785459614
- https://app.asana.com/0/0/1201794806967850
> Solana tweaks

- src/common/utils.js
- src/ethereum/ethEngine.js
- src/ethereum/ethNetwork.js
- src/ethereum/ftminfo.js
---
- https://app.asana.com/0/0/1201824537221449
> Fix getMaxSpendable

- src/ethereum/ethEngine.js
---
- https://app.asana.com/0/0/1201851122332977
> Fix addCustomToken

- src/ethereum/ftminfo.js
Add WFTM, BOO, xBOO, TOMB, TBOND, TSHARE as default tokens.
---
- https://app.asana.com/0/0/1201869369773387
> Add Tomb and Spooky dApp Ecosystem Tokens

- src/ethereum/ethEngine.js
---
- https://app.asana.com/0/0/1202045154064711
> Fix evm fees from external APIs

- src/ethereum/ethEngine.js
- src/ethereum/ethNetwork.js
- src/ethereum/ethTypes.js
- src/ethereum/info/ftminfo.js
---
- https://app.asana.com/0/0/1201945804102397
> Various fixes

- src/ethereum/ethNetwork.js
- src/ethereum/ethTypes.js
- src/ethereum/info/etcInfo.js
Fix blockbook integration so it alone can fully sync a wallet and broadcast transactions. Also make it currency agnostic.
> Fix blockbook support

- src/eos/eosEngine.js
- src/eos/eosInfo.js
- src/eos/telosInfo.js
- src/eos/waxInfo.js
---
- https://app.asana.com/0/0/1202129070713405
> Remove EOS type currencies from their own metaToken info

- src/ethereum/info/ftminfo.js
---
- https://app.asana.com/0/0/1202168796800926
> Add MAI (miMATIC) to fantom metaTokens

- src/ethereum/ethEngine.js
- src/ethereum/ethTypes.js
- src/ethereum/fees/ethMiningFees.js
- src/ethereum/fees/feeProviders.js
- src/ethereum/info/ftminfo.js
---
- https://app.asana.com/0/0/1202208459357185
> Fix urgent issues with fee calculation for EVM chains

- src/common/utils.js
- src/ethereum/ethEngine.js
- src/ethereum/ethPlugin.js
- src/ethereum/ethTypes.js
- src/ethereum/fees/ethMiningFees.js
---
- https://app.asana.com/0/0/1202219160560388
> Fix initial local networkFees assignment

- package.json
- src/common/plugin.js
- src/eos/eosPlugin.js
- src/ethereum/ethPlugin.js
- yarn.lock
---
- https://app.asana.com/0/0/1202249459566086
> Add getTokenId

- src/ethereum/info/ethInfo.js
---
- https://app.asana.com/0/0/1200929999820430
> Renamed PAX -> USDP

- src/ethereum/info/kovanInfo.js
---
- https://app.asana.com/0/0/1202523674748503
> Add more tokens to kovan

- src/polkadot/polkadotEngine.js
- src/polkadot/polkadotTypes.js
This change means we can save progress with each successful response from subscan. 
---
- https://app.asana.com/0/0/1202678419545348
> Completely change queryTransactions

- src/polkadot/polkadotEngine.js
---
- https://app.asana.com/0/0/1202681401455011
> NaN and sent amount denom fixes

- src/xrp/xrpEngine.js
---
- https://app.asana.com/0/0/1202766397266230
> Manage API disconnects in the plugin only

- src/ethereum/ethEngine.js
- src/ethereum/ethNetwork.js
- src/ethereum/ethTypes.js
- src/ethereum/info/ethInfo.js
---
- https://app.asana.com/0/0/1202716183297078
> Fix 0 amount and blockbook queries

- src/ethereum/info/ethInfo.js
---
- https://app.asana.com/0/0/1202764095007352
> Add NOW Token

- src/ethereum/fees/ethMiningFees.js
Necessary for services like Thorchain which require a specific gasPrice but don't specify a gasLimit
---
- https://app.asana.com/0/0/1202834837562700
> Allow specifying only gasPrice or gasLimit for custom fees

- package.json
- src/ethereum/ethEngine.js
- src/ethereum/info/avaxInfo.js
- src/ethereum/info/bscInfo.js
- src/ethereum/info/celoInfo.js
- src/ethereum/info/etcInfo.js
- src/ethereum/info/ethDevInfo.js
- src/ethereum/info/ethInfo.js
- src/ethereum/info/ftmInfo.js
- src/ethereum/info/goerliInfo.js
- src/ethereum/info/kovanInfo.js
- src/ethereum/info/maticInfo.js
- src/ethereum/info/rinkebyInfo.js
- src/ethereum/info/ropstenInfo.js
- src/ethereum/info/rskInfo.js
- yarn.lock
---
- https://app.asana.com/0/0/1202903392787351
> Allow EVM data to be passed through memo field

- src/ethereum/info/ftmInfo.js
Add the L3USD token on Fantom network
> Add FTM token: L3USD

- package.json
- yarn.lock
---
- https://app.asana.com/0/0/1202982191368293
> Upgrade Polkadot SDK

- src/ethereum/fees/ethMiningFees.ts
---
- https://app.asana.com/0/0/1203008188455311
> Fix missing lte import

- src/ethereum/info/celoInfo.ts
---
- https://app.asana.com/0/0/1203059650506803
> Fix Celo server list

- src/common/plugin.ts
- src/ethereum/ethTypes.ts
---
- https://app.asana.com/0/0/1203032795326846
> Fix parseUriCommon protocol parsing

- src/ethereum/ethEngine.ts
---
- https://app.asana.com/0/0/1203074496399250
> Fix boolean coercion

- src/solana/solanaInfo.ts
---
- https://app.asana.com/0/0/1203082709552687
> Update SOL explorer URLs

- src/ethereum/info/ethInfo.ts
---
- https://app.asana.com/0/0/1203068264898923
> Add OGN metaToken (Origin Protocol)

- src/ethereum/ethNetwork.ts
Currently, the ethscan method calls both the rpc servers and ethscan servers. This should be split up so each method is enabled if their respective server URLs are present for a currency.
---
- https://app.asana.com/0/0/1203194225116486
> Split up eth_getTransactionCount query

- src/ethereum/ethNetwork.ts
---
- https://app.asana.com/0/0/1203232900727231
> Disable key in checkTokenBalBlockchair

- .eslintrc.json
- package.json
- src/binance/bnbEngine.ts
- src/common/engine.ts
- src/polkadot/polkadot-sdk-bundle.d.ts
- src/polkadot/polkadotEngine.ts
- src/polkadot/polkadotPlugin.ts
- src/polkadot/polkadotUtils.ts
- src/stellar/stellarEngine.ts
We need the codebase to be clean with all ESLint rules enabled.
---
- https://app.asana.com/0/0/1203287918505552
> Fix linting

- src/ethereum/ethEngine.ts
- src/ethereum/ethNetwork.ts
---
- https://app.asana.com/0/0/1203381477966192
> Extend makeSpend to support token amount metadata for smart-contract calls

- src/common/engine.ts
- src/common/types.ts
- src/eos/eosEngine.ts
- src/ethereum/ethEngine.ts
- src/ethereum/ethNetwork.ts
- src/fio/fioEngine.ts
- src/hedera/hederaEngine.ts
- src/polkadot/polkadotEngine.ts
- src/tezos/tezosEngine.ts
- src/tezos/tezosPlugin.ts
---
- https://app.asana.com/0/0/1203441301125915
> Update currency engine otherData type and clean up ts-expect-errors

- src/common/engine.ts
Actually check the nativeAmounts from spendTargets against the relevant balance from the wallet data. This way negative amounts will pass even when there is a wallet balance of zero.
---
- https://app.asana.com/0/0/1203415142574769
> Fix balance checking in `makeSpendCheck`

- src/tron/tronPlugin.ts
---
- https://app.asana.com/0/0/1203480122472597
> TRX: Fix walletType check in `derivePublicKey`

- src/common/innerPlugin.ts
- src/ethereum/ethPlugin.ts
---
- https://app.asana.com/0/0/1203493795611730
> Expose metaTokens as modern builtin tokens

- src/tron/tronEngine.ts
---
- https://app.asana.com/0/0/1203511522258896
> Add date after broadcasting transaction

- src/tron/tronEngine.ts
---
- https://app.asana.com/0/0/1203570477971687
> Tron: Make sure to check the total native asset cost in makeSpend

- src/ethereum/ethEngine.ts
- src/ethereum/ethTypes.ts
- Changed: Implement accelerate transaction feature using new core API
- https://github.com/EdgeApp/edge-core-js/pull/493
---
- https://app.asana.com/0/0/1203272763143177
> Implement Accelerate Core API

- package.json
- src/common/utils.ts
- src/eos/eosEngine.ts
- src/eos/eosSchema.ts
- src/ethereum/ethEngine.ts
- src/ethereum/ethNetwork.ts
- src/ethereum/ethSchema.ts
- src/ethereum/fees/feeProviders.ts
- yarn.lock
I have managed to test everything except the EOS receive logic. The EOS node we use in `checkIncomingTransactions` simply isn't returning any results, even with incoming transactions, so the cleaner never runs.
---
- https://app.asana.com/0/0/1203483455408818
> Replace all JSON Schema uses with Cleaners

- src/ethereum/ethEngine.ts
- src/xrp/xrpEngine.ts
There are five implementations:
ethereum: Able to remove expensive recursion
ripple: Left comment about logic regarding future token support
zcash: Works as long as network fees remain hardcoded
tron: Unable to remove recursion since the network fee is dependent on the amount sent
polkadot: Same as tron
---
- https://app.asana.com/0/0/1203660431077330
> Audit getMaxSpendable implementations

- src/pluginError.ts
- src/xrp/xrpEngine.ts
- src/xrp/xrpInfo.ts
- src/xrp/xrpPlugin.ts
- src/xrp/xrpTypes.ts
---
- https://app.asana.com/0/0/1203356722869179
> XRP Remove preparePayment and various cleanups

- src/tron/tronEngine.ts
- src/tron/tronInfo.ts
- src/tron/tronPlugin.ts
- src/tron/tronTypes.ts
---
- https://app.asana.com/0/0/1203769262371208
> Tron: Fix derivation path

- src/tron/tronEngine.ts
- src/tron/tronInfo.ts
- src/tron/tronTypes.ts
- src/tron/tronUtils.ts
---
- https://app.asana.com/0/0/1203557533664624
> Tron: Add memo support

- src/ethereum/ethEngine.ts
- src/ethereum/ethPlugin.ts
- Move walletConnectors from ethEngine to ethPlugin
- Fix the wcGetConnections call
CHANGELOG:
fix - missing Active Connections display in WalletConnect
---
- https://app.asana.com/0/0/1203796734787511
> Move walletconnectors into ethPlugin, update walletId call

- src/tron/tronEngine.ts
- src/tron/tronTypes.ts
---
- https://app.asana.com/0/0/1203820792542596
> Fix resource handling and fee calculation for small transactions

- src/tron/tronEngine.ts
- src/tron/tronInfo.ts
- src/tron/tronTypes.ts
---
- https://app.asana.com/0/0/1203880380954144
> Add Tron resource staking

- src/binance/bnbEngine.ts
Implement blank setOtherData method
---
- https://app.asana.com/0/0/1203919484405956
> Fix BNB error alert

- src/common/utils.ts
---
- https://app.asana.com/0/0/1203948188438918
> Add '0x' prefix before passing string to biggystring

- src/xrp/xrpEngine.ts
- src/xrp/xrpInfo.ts
- src/xrp/xrpTypes.ts
Factor in token reserve requirements in makespend and getMaxSpendable
---
- https://app.asana.com/0/0/1203970126286592
- https://app.asana.com/0/0/1203971517303538
> Fix XRP total reserve

- src/ethereum/info/bscInfo.ts
- src/ethereum/info/etcInfo.ts
- src/ethereum/info/ethwInfo.ts
---
- https://app.asana.com/0/0/1203970126892517
> Add tokens for BSC, ETC, and ETHW

- src/ethereum/ethNetwork.ts
---
- https://app.asana.com/0/0/1203962112380410
> Fix double hex conversion for rpc balance calls

- src/ethereum/ethConsts.ts
- src/ethereum/ethEngine.ts
- src/ethereum/ethInfos.ts
- src/ethereum/ethNetwork.ts
- src/ethereum/ethPlugin.ts
- src/ethereum/ethTypes.ts
- src/ethereum/fees/ethMiningFees.ts
- src/ethereum/fees/feeProviders.ts
- src/ethereum/info/avaxInfo.ts
- src/ethereum/info/bscInfo.ts
- src/ethereum/info/celoInfo.ts
- src/ethereum/info/etcInfo.ts
- src/ethereum/info/ethDevInfo.ts
- src/ethereum/info/ethInfo.ts
- src/ethereum/info/ethwInfo.ts
- src/ethereum/info/ftmInfo.ts
- src/ethereum/info/goerliInfo.ts
- src/ethereum/info/kovanInfo.ts
- src/ethereum/info/maticInfo.ts
- src/ethereum/info/optimismInfo.ts
- src/ethereum/info/rinkebyInfo.ts
- src/ethereum/info/ropstenInfo.ts
- src/ethereum/info/rskInfo.ts
- test/engine/feeProvider.test.ts
---
- https://app.asana.com/0/0/1203970651584036
> Add Optimism

- src/common/engine.ts
- src/xrp/xrpEngine.ts
---
- https://app.asana.com/0/0/1203987601665111
> Fix xrp token fee tx

- src/ethereum/ethNetwork.ts
---
- https://app.asana.com/0/0/1204001370454367
> Apply hexToDecimal on eth_call token balance

- src/ethereum/ethEngine.ts
---
- https://app.asana.com/0/0/1204067042367665
> Incorporate L1fee into native amount

- src/common/innerPlugin.ts
- src/polkadot/polkadotInfo.ts
This allows the plugin to identify any minimal environment requirements before returning to the core
---
- https://app.asana.com/0/0/1204070120353789
> Add optional checkEnvironment method to OuterPlugin

- package.json
- src/common/network.ts
- src/common/pixkey.ts
- src/common/smartPay.ts
- src/common/utils.ts
- src/ethereum/ethEngine.ts
- src/ethereum/fees/feeProviders.ts
- src/tron/tronPlugin.ts
- src/tron/tronTypes.ts
- test/engine/feeProvider.test.ts
- test/plugin/smartPay.nettest.ts
- yarn.lock
Add ability to parse and quote PIX codes for payment with Tron/USDT
https://github.com/EdgeApp/edge-core-js/pull/510
none
---
- https://app.asana.com/0/0/1203963906731673
> Smartpay PIX support

- src/common/engine.ts
- fixed: Do not let invalid tokens prevent wallets from loading.
none
none
---
- https://app.asana.com/0/0/1204124238052806
> Do not crash the engine on invalid custom tokens

- src/hedera/hederaInfo.ts
- changed: Use hashscan.io as the Hedera explorer 
none
none
none
---
- https://app.asana.com/0/0/1204127825808129
> Use hashscan.io as the Hedera explorer

- src/ethereum/info/optimismInfo.ts
Optimism allows a gas price lower than 1 gwei
none
none
none
---
- https://app.asana.com/0/0/1204150558060440
> Change the minGasPrice on optimism

- src/common/engine.ts
- src/polkadot/polkadotEngine.ts
- src/stellar/stellarEngine.ts
- src/stellar/stellarInfo.ts
- src/stellar/stellarTypes.ts
- src/xrp/xrpEngine.ts
---
- https://app.asana.com/0/0/1203925052101687
> Prevent sending amounts below min threshold to new addresses

- src/eos/eosPlugin.ts
---
- https://app.asana.com/0/0/1204195353855010
> Fix checkAddress usage

- src/polkadot/polkadotEngine.ts
- src/stellar/stellarEngine.ts
- src/xrp/xrpEngine.ts
---
- https://app.asana.com/0/0/1204207224401814
> Fix minimum required balance handling

- src/eos/eosPlugin.ts
> Remove unnecessary 'hex' encoding argument to `Bytes.from`

- src/fio/fioConst.ts
- src/fio/fioEngine.ts
- src/fio/fioInfo.ts
- src/fio/fioSchema.ts
- src/fio/fioTypes.ts
---
- https://app.asana.com/0/0/1204295865014355
> FIO upgrade cleanups

- src/ethereum/ethNetwork.ts
- src/ethereum/info/avaxInfo.ts
- src/ethereum/info/bscInfo.ts
- src/ethereum/info/celoInfo.ts
- src/ethereum/info/ethInfo.ts
- src/ethereum/info/ftmInfo.ts
- src/ethereum/info/goerliInfo.ts
- src/ethereum/info/maticInfo.ts
- src/ethereum/info/optimismInfo.ts
- src/fio/fioConst.ts
- src/fio/fioEngine.ts
- src/fio/fioInfo.ts
- src/fio/fioSchema.ts
- src/fio/fioTypes.ts
---
- https://app.asana.com/0/0/1204334415499550
> Update EVM RPC node lists

- src/binance/bnbEngine.ts
Update tx fee
Handle broadcast errors
Fix EdgeTransaction signedTx and date handling
---
- https://app.asana.com/0/0/1204205921465195
> BNB Beacon Chain fixes

- src/ethereum/fees/feeProviders.ts
- src/ethereum/info/optimismInfo.ts
Optimism: Add WETH and VELO tokens 
Update networkFees usage to look for pluginId
---
- https://app.asana.com/0/0/1204334418189088
> Prep for Velodrome

- src/zcash/arrrInfo.ts
---
- https://app.asana.com/0/0/1204356062248286
> ARRR: Add missing unsafeBroadcastTx value

- src/ethereum/ethEngine.ts
- src/ethereum/ethTypes.ts
---
- https://app.asana.com/0/0/1204351102858700
> Don't save network fees to disk

- src/ethereum/ethNetwork.ts
- src/ethereum/info/avaxInfo.ts
- src/ethereum/info/bscInfo.ts
- src/ethereum/info/ethInfo.ts
- src/ethereum/info/ftmInfo.ts
- src/ethereum/info/goerliInfo.ts
- src/ethereum/info/maticInfo.ts
- src/ethereum/info/optimismInfo.ts
---
- https://app.asana.com/0/0/1204391922559457
> Update node list

- src/ethereum/info/ethInfo.ts
---
- https://app.asana.com/0/0/1204343809017859
> Add Wrapped FIO (WFIO)

- src/common/smartPay.ts
none
https://github.com/EdgeApp/edge-core-js/pull/522
none
---
- https://app.asana.com/0/0/1204356122004246
> Support PIX minimum

- package.json
- src/binance/bnbEngine.ts
- src/common/types.ts
- src/eos/eosEngine.ts
- src/eos/eosTypes.ts
- src/ethereum/ethTypes.ts
- src/fio/fioConst.ts
- src/fio/fioEngine.ts
- src/hedera/hederaEngine.ts
- src/hedera/hederaTypes.ts
- src/polkadot/polkadotTypes.ts
- src/stellar/stellarEngine.ts
- src/tron/tronEngine.ts
- src/xrp/xrpEngine.ts
- yarn.lock
---
- https://app.asana.com/0/0/1204386783187194
> Update cleaners and audit balance and transaction syncing statuses

- src/ethereum/ethEngine.ts
- src/ethereum/ethPlugin.ts
- test/plugin/fixtures.ts
- Added: ERC-55 checksum address returned by `getFreshAddress` for ethereum plugin
none
none
---
- https://app.asana.com/0/0/1204101187072518
> Add checksum address for `getFreshAddress` to ethereum plugin

- src/zcash/zecEngine.ts
The zcash and pirate sdks will occasionally crash because of database access bugs. This PR doesn't promise to fix that but instead hopes to avoid contributing to the problem by making sure we're only doing one DB method at a time
---
- https://app.asana.com/0/0/1203714696805325
- https://app.asana.com/0/0/1204482356154633
> Add mutex to balance and transaction query

- src/fio/fioInfo.ts
---
- https://app.asana.com/0/0/1204496998601659
> Update FIO nodes

- src/algorand/AlgorandEngine.ts
- src/algorand/algorandTypes.ts
---
- https://app.asana.com/0/0/1204518940852204
> Algorand: Support signing multiple transactions in wallet connect request

- src/ethereum/ethEngine.ts
- src/ethereum/ethTypes.ts
- src/ethereum/fees/ethMiningFees.ts
- src/ethereum/info/zksyncInfo.ts
- test/engine/feeProvider.test.ts
none
none
none
---
- https://app.asana.com/0/0/1204535275865679
> Fix zkSync gas limit issue by always using eth_estimateGas

- src/fio/fioEngine.ts
---
- https://app.asana.com/0/0/1204525927886865
> Fix pubkey in request and obt data

- src/zcash/zecPlugin.ts
---
- https://app.asana.com/0/0/1204535089316845
> ZEC/ARRR Handle import key birthday height

- src/ethereum/EthereumEngine.ts
---
- https://app.asana.com/0/0/1204597701751037
> Handle null gas price in txRpcParamsToSpendInfo 

- src/tron/tronTypes.ts
- src/tron/tronUtils.ts
Also resolve a strict cleaner issue for token transaction processing
---
- https://app.asana.com/0/0/1204622945920916
> Pass nativeAmount directly to encoder

- src/fio/FioEngine.ts
---
- https://app.asana.com/0/0/1204663161710905
> FIO: Handle empty otherParams objects as null

- src/fio/FioEngine.ts
- src/fio/fioConst.ts
- Fixed: Added transaction processing for FIO name registration actions
none
none
---
- https://app.asana.com/0/0/1204507615237140
> Include regaddress FIO actions as spend transactions

- src/ethereum/EthereumEngine.ts
- src/ethereum/EthereumNetwork.ts
- src/ethereum/ethereumTypes.ts
- Changed: Re-enable token transaction accelerate for EVM currencies
none
none
---
- https://app.asana.com/0/0/1204597702128318
> Fix Token Accelerate Tx (quick hack fix)

- src/fio/FioEngine.ts
---
- https://app.asana.com/0/0/1204496663052481
> Add getMaxSpendable to FioEngine

- src/fio/FioEngine.ts
---
- https://app.asana.com/0/0/1204740435185934
> Use locked balance from balances object for getMaxSpendable

- src/fio/FioEngine.ts
---
- https://app.asana.com/0/0/1204740435185931
> Fix insufficient funds check when unstaking FIO

- src/ethereum/EthereumEngine.ts
- src/ethereum/ethereumTypes.ts
- src/ethereum/fees/ethMiningFees.ts
- Fixed: Fix broken max-spend for zkSync
none
none
---
- https://app.asana.com/0/0/1204825785199825
- https://app.asana.com/0/0/1204829809536930
> Fix broken max-spend for zkSync

- src/ethereum/EthereumNetwork.ts
- src/ethereum/ethereumInfos.ts
- src/ethereum/info/pulsechainInfo.ts
- Added: Add PulseChain (PLS)
none
none
---
- https://app.asana.com/0/0/1204613856974983
> Add PulseChain

- .travis.yml
- package.json
- yarn.lock
---
- https://app.asana.com/0/0/1204870484299858
> Upgrade @polkadot/api

- src/tron/TronTools.ts
Disable PIX for TRX sends
none
none
---
- https://app.asana.com/0/0/1204816505094895
> Disable PIX codes for TRX

- src/ethereum/info/ethereumInfo.ts
---
- https://app.asana.com/0/0/1204988132396842
> Add new GALA token

- src/fio/fioInfo.ts
- Fixed: FIO transaction reliability issues resolved by adding more historical nodes
none
none
---
- https://app.asana.com/0/0/1204848803117133
> Add more historical nodes to FIO

- src/fio/FioEngine.ts
- src/fio/fioError.ts
- src/fio/fioInfo.ts
---
- https://app.asana.com/0/0/1205057984776312
> Remove eosmadrid

- src/ethereum/EthereumEngine.ts
- src/ethereum/EthereumNetwork.ts
- src/ethereum/ethereumTypes.ts
- src/ethereum/fees/ethMiningFees.ts
- src/ethereum/info/optimismInfo.ts
---
- https://app.asana.com/0/0/1205083666279890
> Wallet connect and Optimism gas fixes

- src/ripple/rippleInfo.ts
---
- https://app.asana.com/0/0/1205010136007859
> Update XRP explorer URL

- src/fio/FioEngine.ts
- src/fio/fioConst.ts
- Fixed: Bug in FIO causing missing historical transactions (first page of transactions).
- Fixed: Improve FIO transaction history fetching from history nodes by using the nodes with the highest action sequence number.
none
none
---
- https://app.asana.com/0/0/1204820125824456
> Fix FIO history sync

- src/ethereum/info/fantomInfo.ts
---
- https://app.asana.com/0/0/1205057756911262
> Add Fantom tokens listed on Axelarscan

- src/algorand/AlgorandEngine.ts
- src/algorand/AlgorandTools.ts
- src/binance/BinanceEngine.ts
- src/binance/BinanceTools.ts
- src/common/CurrencyEngine.ts
- src/common/uriHelpers.ts
- src/common/utils.ts
- src/eos/EosEngine.ts
- src/eos/EosTools.ts
- src/ethereum/EthereumEngine.ts
- src/ethereum/EthereumTools.ts
- src/fio/FioEngine.ts
- src/fio/FioTools.ts
- src/hedera/HederaEngine.ts
- src/hedera/HederaTools.ts
- src/polkadot/PolkadotEngine.ts
- src/polkadot/PolkadotTools.ts
- src/ripple/RippleEngine.ts
- src/ripple/RippleTools.ts
- src/solana/SolanaEngine.ts
- src/solana/SolanaTools.ts
- src/stellar/StellarEngine.ts
- src/stellar/StellarTools.ts
- src/tezos/TezosEngine.ts
- src/tron/TronEngine.ts
- src/tron/TronTools.ts
- src/zcash/ZcashEngine.ts
- src/zcash/ZcashTools.ts
- changed: Allow custom tokens to overwrite built-in tokens.
none
none
---
- https://app.asana.com/0/0/1204585357987354
> Token upgrade

- src/ripple/RippleEngine.ts
fixed: Incorrect XRP sign after sending tokens 
none
none
---
- https://app.asana.com/0/0/1205346178661961
> Fix incorrect sign on spend amounts

- src/ethereum/info/binancesmartchainInfo.ts
- src/ethereum/info/ethereumInfo.ts
added: ARB, PAXG, BUSD
none
none
---
- https://app.asana.com/0/0/1205281746792934
> Add recommended tokens

- src/filecoin/FilecoinEngine.ts
- src/filecoin/Filscan.ts
- src/polkadot/info/liberlandInfo.ts
- src/polkadot/info/liberlandTestnetInfo.ts
---
- https://app.asana.com/0/0/1205386902005031
> Fix transaction query status for FIL and LLD

- src/polkadot/PolkadotEngine.ts
- src/polkadot/info/liberlandInfo.ts
- src/polkadot/info/liberlandTestnetInfo.ts
- src/polkadot/info/polkadotInfo.ts
- src/polkadot/polkadotTypes.ts
---
- https://app.asana.com/0/0/1205412889551008
> Fix max spend in Polkadot engine

- src/filecoin/FilecoinEngine.ts
- src/filecoin/Filfox.ts
- src/filecoin/Filscan.ts
- src/filecoin/filecoinInfo.ts
- src/filecoin/filecoinTypes.ts
- added: Integrate Filfox for Filecoin transaction scanning
none
none
---
- https://app.asana.com/0/0/1205428175687868
> Integrate Filfox for Filecoin transaction scanning

- src/filecoin/FilecoinEngine.ts
- fixed: Incorrectly identifying send-to-self transactions as receives from the network
none
none
> Incorrectly identifying send-to-self transactions as receives from the network

- src/ethereum/info/avalancheInfo.ts
- src/ethereum/info/ethereumInfo.ts
Add PYUSD on Ethereum
Add USDT on AVAX
---
- https://app.asana.com/0/0/1205266575124988
- https://app.asana.com/0/0/1205230281940007
> Add tokens

- src/ethereum/info/pulsechainInfo.ts
---
- https://app.asana.com/0/0/1205443236752765
> Switch from Scan Pulsechain to Beacon Pulsechain explorer

- package.json
- src/piratechain/PiratechainEngine.ts
- src/piratechain/PiratechainTools.ts
- src/react-native.ts
- yarn.lock
---
- https://app.asana.com/0/0/1205419516159280
> Disable Piratechain

- src/zcash/ZcashEngine.ts
- src/zcash/zcashTypes.ts
---
- https://app.asana.com/0/0/1205041005078327
> Fix Zcash memo handling

- src/ethereum/EthereumEngine.ts
- src/ethereum/fees/ethMiningFees.ts
---
- https://app.asana.com/0/0/1205494934472419
> Fix data field handling

- CHANGELOG.md
- src/zcash/zcashInfo.ts
---
- https://app.asana.com/0/0/1205522315371793
> Update Zcash address explorer

- src/ethereum/EthereumEngine.ts
---
- https://app.asana.com/0/0/1205531062861909
> Pass wallet connect transaction data as EdgeMemo

- package.json
- src/zcash/ZcashEngine.ts
- src/zcash/zcashTypes.ts
- yarn.lock
---
- https://app.asana.com/0/0/1205534330730646
> Use sapling address from deriveUnifiedAddresses

- src/filecoin/FilecoinEngine.ts
- src/filecoin/filecoinInfo.ts
- src/filecoin/filecoinTypes.ts
- fixed: Do not crash if BigInt is not present.
- fixed: Block Filecoin when BigInt is not present.
none
none
---
- https://app.asana.com/0/0/1205533353868797
> Fix filecoin import

- CHANGELOG.md
- src/zcash/zcashInfo.ts
---
- https://app.asana.com/0/0/1205534205786205
> Use sapling address compatible explorer link

- CHANGELOG.md
- src/zcash/zcashInfo.ts
none
none
---
- https://app.asana.com/0/0/1205553400857731
> Temporarily disable zcash memos

- CHANGELOG.md
- src/ethereum/info/optimismInfo.ts
---
- https://app.asana.com/0/0/1205443361322803
> Add VELO v2 support

- src/tron/TronEngine.ts
- src/tron/tronTypes.ts
---
- https://app.asana.com/0/0/1205419517607650
> Add WithdrawExpireUnfreeze support

- CHANGELOG.md
- src/stellar/StellarEngine.ts
Ensure fees are always using standard when unspecified
none
none
none
---
- https://app.asana.com/0/0/1205354125379572
> Fix max spend for xlm

- CHANGELOG.md
- src/filecoin/filecoinInfo.ts
none
none
---
- https://app.asana.com/0/0/1205651834639668
> Switch Filecoin to a working block explorer

- CHANGELOG.md
- package.json
- src/tron/TronEngine.ts
- src/tron/tronTypes.ts
- yarn.lock
- added: EdgeTxAction tagging to TRX freeze/unfreeze contract call transactions
https://github.com/EdgeApp/edge-core-js/pull/567
none
---
- https://app.asana.com/0/0/1205412692015302
> Add txInfo to TronEngine

- package.json
- src/react-native.ts
- src/zcash/ZcashEngine.ts
- src/zcash/zcashInfo.ts
- src/zcash/zcashTypes.ts
- yarn.lock
---
- https://app.asana.com/0/0/1205676904389987
> Zcash v2 followup fixes

- CHANGELOG.md
- src/filecoin/FilecoinEngine.ts
none
none
---
- https://app.asana.com/0/0/1205453740913639
> Fix Filecoin `makeSpend` fee estimation

- CHANGELOG.md
- src/zcash/ZcashEngine.ts
none
none
---
- https://app.asana.com/0/0/1205756123988866
> Fix new zcash tx 0-date race condition

- CHANGELOG.md
- src/filecoin/FilecoinTools.ts
- src/filecoin/calibrationInfo.ts
- src/filecoin/filecoinInfo.ts
- src/filecoin/filecoinTypes.ts
- src/index.ts
none
none
---
- https://app.asana.com/0/0/1205724542492733
> Add Calibration Filecoin Testnet

- CHANGELOG.md
- src/filecoin/FilecoinEngine.ts
- src/filecoin/Filfox.ts
none
none
---
- https://app.asana.com/0/0/1205453740913620
> Improve Filecoin transaction querying

- .gitignore
- CHANGELOG.md
- edge-currency-accountbased.d.ts
- package.json
- src/declare-modules.d.ts
- src/globals.ts
- src/index.ts
none
none
---
- https://app.asana.com/0/0/1205752857432320
> Provide proper type exports for this library

- CHANGELOG.md
- src/filecoin/FilecoinEngine.ts
none
none
---
- https://app.asana.com/0/0/1205789457521998
> Filecoin resync bugs

- CHANGELOG.md
- src/filecoin/FilecoinEngine.ts
none
none
---
- https://app.asana.com/0/0/1205794728237032
> Fix getMaxSpendable for Filecoin

- src/piratechain/PiratechainEngine.ts
---
- https://app.asana.com/0/0/1205848598553276
> Convert ARRR alias to hex

- CHANGELOG.md
- src/ethereum/info/ethereumInfo.ts
none
none
---
- https://app.asana.com/0/0/1205466694315860
> Fix contract address for PYUSD

- CHANGELOG.md
- package.json
- src/common/utils.ts
- src/ethereum/EthereumEngine.ts
- src/ethereum/EthereumNetwork.ts
- src/ethereum/fees/ethMiningFees.ts
- yarn.lock
none
none
---
- https://app.asana.com/0/0/1205751906499650
> Support type 2 EVM transaction with EIP1559 parameters

- CHANGELOG.md
- package.json
- src/ethereum/EthereumNetwork.ts
- src/ethereum/abi/ETH_BAL_CHECKER_ABI.json
- src/ethereum/ethereumTypes.ts
- src/ethereum/info/binancesmartchainInfo.ts
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/info/polygonInfo.ts
- yarn.lock
none
Use eth-balance-checker contracts for batch token balance queries for ETH, BSC, and MATIC
---
- https://app.asana.com/0/0/1205654034220624
> On-Chain Batch Balance Query

- CHANGELOG.md
- src/piratechain/PiratechainEngine.ts
---
- https://app.asana.com/0/0/1205879859988591
> Restart synchronizer if it stop providing status updates

- CHANGELOG.md
- src/ethereum/EthereumNetwork.ts
- src/ethereum/info/polygonInfo.ts
---
- https://app.asana.com/0/0/1205865331204026
> Update bridged USDC currency code to USDC.e

- src/cosmos/CosmosTools.ts
---
- https://app.asana.com/0/0/1205905233752262
> Fix CosmosEngine import path

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
- src/ethereum/fees/ethMiningFees.ts
none
none
---
- https://app.asana.com/0/0/1205910906422424
> Use transaction type 0 for currencies which do not support EIP-1559

- src/cosmos/CosmosTools.ts
- src/cosmos/cosmosRegistry.ts
- src/cosmos/cosmosTypes.ts
- src/cosmos/cosmosUtils.ts
- src/cosmos/info/thorchainruneInfo.ts
---
- https://app.asana.com/0/0/1205935849121933
> Add API keys to client initialization

- CHANGELOG.md
- scripts/cosmos-ts-protos/generate-ts-protos.ts
- src/common/types.ts
- src/cosmos/CosmosEngine.ts
- src/cosmos/cosmosRegistry.ts
- src/cosmos/cosmosTypes.ts
- src/cosmos/cosmosUtils.ts
- src/cosmos/info/proto/thorchainrune/thorchain/v1/common/common.ts
- src/cosmos/info/proto/thorchainrune/thorchain/v1/x/thorchain/types/msg_deposit.ts
- src/ripple/RippleEngine.ts
- src/ripple/rippleTypes.ts
none
none
---
- https://app.asana.com/0/0/1205865478804253
> Add Thorchain MsgDeposit support

- CHANGELOG.md
- src/common/utils.ts
- src/ethereum/EthereumTools.ts
- src/ethereum/ethereumTypes.ts
- src/ethereum/info/ethereumInfo.ts
none
none
---
- https://app.asana.com/0/0/1205920007236365
> ENS Name Resolution

- CHANGELOG.md
- src/cosmos/CosmosEngine.ts
- src/cosmos/cosmosTypes.ts
- src/cosmos/cosmosUtils.ts
- src/cosmos/info/thorchainruneInfo.ts
none
none
---
- https://app.asana.com/0/0/1205930238457636
> Replace Shapeshift API with native RPC searchTx

- src/cosmos/cosmosRegistry.ts
---
- https://app.asana.com/0/0/1206002958375303
> Fix deposit alias

- CHANGELOG.md
- src/ethereum/info/fantomInfo.ts
- src/ethereum/info/polygonInfo.ts
none
none
---
- https://app.asana.com/0/0/1205997135183157
> Add use of Pokt RPCs for fantom and polygon

- CHANGELOG.md
- src/ethereum/info/avalancheInfo.ts
none
none
---
- https://app.asana.com/0/0/1206013878484625
> Update Avalanche to use avascan.info

- src/ethereum/EthereumNetwork.ts
- src/ethereum/info/filecoinFevmCalibrationInfo.ts
- src/ethereum/info/filecoinFevmInfo.ts
- src/ethereum/networkAdapters/AmberdataAdapter.ts
- src/ethereum/networkAdapters/BlockbookAdapter.ts
- src/ethereum/networkAdapters/BlockchairAdapter.ts
- src/ethereum/networkAdapters/BlockcypherAdapter.ts
- src/ethereum/networkAdapters/EvmScanAdapter.ts
- src/ethereum/networkAdapters/FilfoxAdapter.ts
- src/ethereum/networkAdapters/RpcAdapter.ts
- src/ethereum/networkAdapters/types.ts
- src/filecoin/FilecoinTools.ts
none
none
---
- https://app.asana.com/0/0/1205962585703141
> Filecoin FEVM fixes

- src/cosmos/CosmosEngine.ts
- src/cosmos/info/thorchainruneInfo.ts
---
- https://app.asana.com/0/0/1206053210000460
> (cosmos-based) Add unconfirmed nonce handling

- CHANGELOG.md
- src/cosmos/CosmosEngine.ts
- src/cosmos/cosmosTypes.ts
none
none
---
- https://app.asana.com/0/0/1206081446482907
> Implement Cosmos getMaxTx

- CHANGELOG.md
- package.json
- src/solana/SolanaEngine.ts
- src/solana/SolanaTools.ts
- src/solana/solanaInfo.ts
- src/solana/solanaTypes.ts
- yarn.lock
none
none
---
- https://app.asana.com/0/0/1205407182344883
> Solana: Add token support

- CHANGELOG.md
- src/common/CurrencyEngine.ts
- src/common/types.ts
- src/cosmos/CosmosEngine.ts
- src/cosmos/CosmosTools.ts
- src/cosmos/cosmosTypes.ts
- src/cosmos/cosmosUtils.ts
- src/cosmos/info/osmosisInfo.ts
none
none
---
- https://app.asana.com/0/0/1205930490513444
> Add token support (Cosmos-based)

- src/cosmos/CosmosEngine.ts
- src/cosmos/CosmosTools.ts
- src/cosmos/cosmosUtils.ts
- src/cosmos/info/osmosisInfo.ts
---
- https://app.asana.com/0/0/1206081708692802
> Apply apikey to archive node url

- src/ethereum/EthereumEngine.ts
- src/solana/solanaInfo.ts
---
- https://app.asana.com/0/0/1206099991498390
> Fix 'latests' typo

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
- src/ethereum/ethereumTypes.ts
- src/ethereum/fees/ethMiningFees.ts
- src/ethereum/info/avalancheInfo.ts
- src/ethereum/info/binancesmartchainInfo.ts
- src/ethereum/info/celoInfo.ts
- src/ethereum/info/ethDevInfo.ts
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/info/ethereumclassicInfo.ts
- src/ethereum/info/ethereumpowInfo.ts
- src/ethereum/info/fantomInfo.ts
- src/ethereum/info/filecoinFevmCalibrationInfo.ts
- src/ethereum/info/filecoinFevmInfo.ts
- src/ethereum/info/goerliInfo.ts
- src/ethereum/info/kovanInfo.ts
- src/ethereum/info/optimismInfo.ts
- src/ethereum/info/polygonInfo.ts
- src/ethereum/info/pulsechainInfo.ts
- src/ethereum/info/rinkebyInfo.ts
- src/ethereum/info/ropstenInfo.ts
- src/ethereum/info/rskInfo.ts
- src/ethereum/info/zksyncInfo.ts
none
none
---
- https://app.asana.com/0/0/1206107009687915
> Revert two gwei minimum base-fee logic

- CHANGELOG.md
- package.json
- src/cosmos/CosmosEngine.ts
- src/cosmos/cosmosTypes.ts
- src/cosmos/cosmosUtils.ts
- src/cosmos/info/coreumInfo.ts
- src/cosmos/info/osmosisInfo.ts
- yarn.lock
none
none
---
- https://app.asana.com/0/0/1206155049198539
> Update Osmosis and Coreum rpc endpoints

- CHANGELOG.md
- src/ethereum/info/avalancheInfo.ts
- src/ethereum/info/fantomInfo.ts
- src/ethereum/info/optimismInfo.ts
none
Add ethBalCheckerContract to FTM, AVAX, OP
---
- https://app.asana.com/0/0/1206163082834095
> Add ethBalCheckerContract to FTM, AVAX, OP

- CHANGELOG.md
- src/solana/solanaInfo.ts
---
- https://app.asana.com/0/0/1206185605352700
> Add BONK (Solana)

- CHANGELOG.md
- src/ethereum/fees/ethMiningFees.ts
- src/ethereum/info/fantomInfo.ts
- src/ethereum/info/filecoinFevmCalibrationInfo.ts
- src/ethereum/info/pulsechainInfo.ts
none
none
---
- https://app.asana.com/0/0/1206163094464526
> Fix various regressions and bugs caused by recent refactors

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
- src/ethereum/EthereumNetwork.ts
- src/ethereum/fees/ethMiningFees.ts
- src/ethereum/info/fantomInfo.ts
- src/ethereum/networkAdapters/RpcAdapter.ts
none
none
---
- https://app.asana.com/0/0/1206155054149922
> EIP-1559 fixes

- CHANGELOG.md
- src/ethereum/info/optimismInfo.ts
---
- https://app.asana.com/0/0/1206200690226790
> (Optimism) Add native USDC and rename wrapped version to USDC.e

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
- src/ethereum/fees/ethMiningFees.ts
none
none
---
- https://app.asana.com/0/0/1206225248558900
> Fix accelerate for EIP1559 transactions

- CHANGELOG.md
- src/ethereum/fees/ethMiningFees.ts
none
none
---
- https://app.asana.com/0/0/1206238073586101
> Fix `makeSpend` regression for non-EIP-1559 transactions

- CHANGELOG.md
- src/ethereum/networkAdapters/RpcAdapter.ts
none
none
---
- https://app.asana.com/0/0/1206241346288025
> Remove getBaseFeePerGas method on RpcAdaptor for non-EIP-1559 chains

- CHANGELOG.md
- src/ethereum/info/optimismInfo.ts
---
- https://app.asana.com/0/0/1206227564988174
> (Optimism) Add Tarot

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
---
- https://app.asana.com/0/0/1206267426778174
> Remove arbitrary limit of 5 unconfirmed transactions

- CHANGELOG.md
- src/tron/TronEngine.ts
none
none
---
- https://app.asana.com/0/0/1205980933166836
> Stop saving 0-fee EdgeTransactions for trc20 transactions

- CHANGELOG.md
- src/cosmos/CosmosEngine.ts
---
- https://app.asana.com/0/0/1206305125892145
> Add Cosmos staking balance and signMessage

- CHANGELOG.md
- src/cosmos/CosmosEngine.ts
- src/cosmos/cosmosTypes.ts
- src/cosmos/info/thorchainruneInfo.ts
none
none
---
- https://app.asana.com/0/0/1206116889339891
> Use dynamic fees from thornode

- CHANGELOG.md
- src/solana/SolanaEngine.ts
- src/solana/solanaInfo.ts
- src/solana/solanaTypes.ts
---
- https://app.asana.com/0/0/1206425713692374
> Add versioned transaction parsing

- CHANGELOG.md
- src/piratechain/piratechainInfo.ts
---
- https://app.asana.com/0/0/1206446541726199
> Add memoType to Piratechain

- CHANGELOG.md
- package.json
- src/cosmos/cosmosUtils.ts
- yarn.lock
---
- https://app.asana.com/0/0/1206448434494335
> (Cosmos) Ignore events with nonstandard hyphenated denoms

- CHANGELOG.md
- src/solana/SolanaEngine.ts
none
none
---
- https://app.asana.com/0/0/1206460200400115
> Add rent threshold to Solana engine

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
- src/ethereum/abi/NODE_INTERFACE_ABI.json
- src/ethereum/ethereumInfos.ts
- src/ethereum/ethereumTypes.ts
- src/ethereum/fees/ethMiningFees.ts
- src/ethereum/info/arbitrumInfo.ts
- src/ethereum/info/avalancheInfo.ts
- src/ethereum/info/baseInfo.ts
- src/ethereum/info/binancesmartchainInfo.ts
- src/ethereum/info/celoInfo.ts
- src/ethereum/info/ethDevInfo.ts
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/info/ethereumclassicInfo.ts
- src/ethereum/info/ethereumpowInfo.ts
- src/ethereum/info/fantomInfo.ts
- src/ethereum/info/filecoinFevmCalibrationInfo.ts
- src/ethereum/info/filecoinFevmInfo.ts
- src/ethereum/info/goerliInfo.ts
- src/ethereum/info/kovanInfo.ts
- src/ethereum/info/optimismInfo.ts
- src/ethereum/info/polygonInfo.ts
- src/ethereum/info/pulsechainInfo.ts
- src/ethereum/info/rinkebyInfo.ts
- src/ethereum/info/ropstenInfo.ts
- src/ethereum/info/rskInfo.ts
- src/ethereum/info/zksyncInfo.ts
- src/ethereum/networkAdapters/EvmScanAdapter.ts
none
none
---
- https://app.asana.com/0/0/1205999316796685
> Add Arbitrum One and Base

- CHANGELOG.md
- scripts/cosmos-ts-protos/generate-chain-json.ts
- src/cosmos/cosmosInfos.ts
- src/cosmos/info/axelarInfo.ts
- src/cosmos/info/chain-json/axelar.json
- src/cosmos/info/chain-json/cosmoshub.json
- src/cosmos/info/cosmoshubInfo.ts
none
none
---
- https://app.asana.com/0/0/1206424694524219
> Add Cosmos Hub and Axelar

- CHANGELOG.md
- src/ripple/rippleInfo.ts
none
none
---
- https://app.asana.com/0/0/1205787718936175
> Add Bitstamp EUR token for Ripple

- src/algorand/AlgorandEngine.ts
- src/common/types.ts
- src/cosmos/CosmosEngine.ts
- src/cosmos/cosmosRegistry.ts
- src/cosmos/cosmosTypes.ts
- src/cosmos/cosmosUtils.ts
- src/ethereum/EthereumEngine.ts
none
none
---
- https://app.asana.com/0/0/1206424694524216
> Add WalletConnect support to CosmosEngine

- CHANGELOG.md
- src/common/tokenHelpers.ts
- src/ethereum/info/binancesmartchainInfo.ts
- test/utils/tokenHelpers.test.ts
none
none
---
- https://app.asana.com/0/0/1205982483630112
> Add several BSC tokens

- CHANGELOG.md
- src/cosmos/CosmosEngine.ts
- src/cosmos/CosmosTools.ts
- src/cosmos/cosmosUtils.ts
- src/cosmos/info/coreumInfo.ts
- test/utils/parseCoins.test.ts
none
none
---
- https://app.asana.com/0/0/1206548993975489
> Add Coreum tokens

- CHANGELOG.md
- src/cosmos/CosmosEngine.ts
- src/cosmos/CosmosTools.ts
- src/cosmos/info/coreumInfo.ts
---
- https://app.asana.com/0/0/1206638821734114
> Update Cosmos token handling

- CHANGELOG.md
- src/tron/TronEngine.ts
- src/tron/tronTypes.ts
---
- https://app.asana.com/0/0/1206649147969977
> Incorporate energy penalty into trc20 fee calculation

- CHANGELOG.md
- src/ethereum/info/arbitrumInfo.ts
none
none
---
- https://app.asana.com/0/0/1206631221096885
> Add ARB tokens

- src/ethereum/EthereumEngine.ts
- src/ethereum/fees/ethMiningFees.ts
---
- https://app.asana.com/0/0/1206670220740547
> Cache and fuzz Arbitrum fees

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
- src/ethereum/EthereumNetwork.ts
none
none
---
- https://app.asana.com/0/0/1206683853627501
> Fix L2 rollup fee in balance check 

- CHANGELOG.md
- src/ethereum/info/ethereumclassicInfo.ts
---
- https://app.asana.com/0/0/1206686685006459
> Replace ETC rpc

- CHANGELOG.md
- src/algorand/algorandInfo.ts
---
- https://app.asana.com/0/0/1206681388150918
> Update Algorand explorer urls

- CHANGELOG.md
- src/ethereum/networkAdapters/PulsechainScanAdapter.ts
none
none
---
- https://app.asana.com/0/0/1206726369157274
> Fix timestamp data type conversion in PulsechainScanAdapter

- CHANGELOG.md
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/info/fantomInfo.ts
- src/ethereum/info/goerliInfo.ts
- src/ethereum/info/polygonInfo.ts
- src/solana/solanaInfo.ts
---
- https://app.asana.com/0/0/1206746745441541
> Update pokt network url

- src/solana/SolanaEngine.ts
- src/solana/solanaInfo.ts
- src/solana/solanaTypes.ts
none
none
---
- https://app.asana.com/0/0/1206671189992541
> Replace deprecated rpc methods

- CHANGELOG.md
- src/fio/FioEngine.ts
- src/fio/fioSchema.ts
Add back 'trnsfiopubky' tx type and fix processTransaction logic
none
none
---
- https://app.asana.com/0/0/1206701030854365
> Fix missing FIO transactions

- src/polkadot/PolkadotEngine.ts
---
- https://app.asana.com/0/0/1206780149265528
> Add getFreshAddress to PolkadotEngine

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
- src/ethereum/networkAdapters/RpcAdapter.ts
none
none
---
- https://app.asana.com/0/0/1206764328280634
> Fix getMaxSpendable for L2s

- src/fio/FioEngine.ts
- test/fio/fioengine.test.ts
- test/fixtures/fioactions.json
none
none
---
- https://app.asana.com/0/0/1206771367992292
> Refactor FIO processTransaction for unit testing

- .eslintignore
- package.json
---
- https://app.asana.com/0/0/1206854385865126
> Update eslint config

- CHANGELOG.md
- src/polkadot/PolkadotEngine.ts
---
- https://app.asana.com/0/0/1206872408707650
> Update subscan transfers url

- CHANGELOG.md
- src/ethereum/networkAdapters/FilfoxAdapter.ts
- src/filecoin/Filfox.ts
none
none
---
- https://app.asana.com/0/0/1206163121337317
> Use Ethereum transaction hash for FEMV txid

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
- src/ethereum/ethereumTypes.ts
- src/ethereum/fees/ethMiningFees.ts
- src/ethereum/info/baseInfo.ts
- src/ethereum/info/optimismInfo.ts
- src/ethereum/networkAdapters/EvmScanAdapter.ts
---
- https://app.asana.com/0/0/1206844514368991
> Add EIP-4844 fee calculation

- CHANGELOG.md
- src/filecoin/FilecoinEngine.ts
- src/filecoin/filecoinTypes.ts
none
none
---
- https://app.asana.com/0/0/1206892270758884
> Add FilecoinInitOptions with GLIF API key to FilecoinEngine

- CHANGELOG.md
- package.json
- src/cardano/CardanoEngine.ts
- src/cardano/CardanoTools.ts
- src/cardano/cardanoInfo.ts
- src/cardano/cardanoTestnetInfo.ts
- src/cardano/cardanoTypes.ts
- src/index.ts
- test/fio/cardanoTxProcessing.test.ts
- test/fixtures/cardanoFixtures.json
- webpack.config.js
- yarn.lock
---
- https://app.asana.com/0/0/1206574606763075
> Add Cardano

- CHANGELOG.md
- cli/cliContext.ts
- cli/commands/selectPlugin.ts
- package.json
- src/ethereum/networkAdapters/EvmScanAdapter.ts
- test/builtinTokens.test.ts
- test/engine/engine.test.ts
- test/eos/activation.test.ts
- test/plugin/smartPay.nettest.ts
- test/tezos/engine.test.ts
- test/xrp/plugin.test.ts
- yarn.lock
none
none
---
- https://app.asana.com/0/0/1206892270756766
> Mark failed transactions appropriately within evmscan fetchTx

- CHANGELOG.md
- package.json
- src/algorand/algorandInfo.ts
- src/algorand/algorandTestnetInfo.ts
- src/ethereum/info/arbitrumInfo.ts
- src/ethereum/info/avalancheInfo.ts
- src/ethereum/info/baseInfo.ts
- src/ethereum/info/binancesmartchainInfo.ts
- src/ethereum/info/celoInfo.ts
- src/ethereum/info/ethDevInfo.ts
- src/ethereum/info/ethereumCommonInfo.ts
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/info/ethereumclassicInfo.ts
- src/ethereum/info/ethereumpowInfo.ts
- src/ethereum/info/fantomInfo.ts
- src/ethereum/info/filecoinFevmCalibrationInfo.ts
- src/ethereum/info/filecoinFevmInfo.ts
- src/ethereum/info/goerliInfo.ts
- src/ethereum/info/kovanInfo.ts
- src/ethereum/info/optimismInfo.ts
- src/ethereum/info/polygonInfo.ts
- src/ethereum/info/pulsechainInfo.ts
- src/ethereum/info/rinkebyInfo.ts
- src/ethereum/info/ropstenInfo.ts
- src/ethereum/info/rskInfo.ts
- src/ethereum/info/zksyncInfo.ts
- src/solana/solanaInfo.ts
- yarn.lock
https://github.com/EdgeApp/edge-core-js/pull/592 Would be nice to have
none
---
- https://app.asana.com/0/0/1206924839994697
> Add modern fee templates to currency infos

- src/ethereum/networkAdapters/EvmScanAdapter.ts
- test/ethereum/network/allTokensMapFixture.ts
- test/ethereum/network/currencyInfoFixture.ts
- test/ethereum/network/evmScanTxProcessing.cases.ts
- test/ethereum/network/evmScanTxProcessing.test.ts
- test/fake/FakeTools.ts
none
none
---
- https://app.asana.com/0/0/1206966606672147
> Test processEvmScanTransaction

- CHANGELOG.md
- src/cardano/CardanoEngine.ts
none
Fix insufficient funds handling in the Cardano engine.
---
- https://app.asana.com/0/0/1206951571997135
> Cardano insufficient funds

- README.md
none
none
---
- https://app.asana.com/0/0/1207103660329034
> Document react-native-zcash and react-native-piratechain requirements

- CHANGELOG.md
- src/polkadot/info/liberlandInfo.ts
---
- https://app.asana.com/0/0/1207093994213722
> Liberland: Add additional rpc

- CHANGELOG.md
- src/ethereum/info/binancesmartchainInfo.ts
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/info/polygonInfo.ts
- src/ethereum/info/zksyncInfo.ts
none
none
---
- https://app.asana.com/0/0/1206984670485284
> Add default tokens

- CHANGELOG.md
- src/common/smartPay.ts
---
- https://app.asana.com/0/0/1206844514368984
> Adjust Smartpay types

- CHANGELOG.md
- package.json
- src/hedera/HederaEngine.ts
- src/hedera/HederaTools.ts
- src/hedera/hederaInfo.ts
- src/hedera/hederaTestnetInfo.ts
- src/hedera/hederaTypes.ts
- src/hedera/hederaUtils.ts
- yarn.lock
none
none
---
- https://app.asana.com/0/0/1206745835636212
> Hedera - Add auto activation

- CHANGELOG.md
- package.json
- src/react-native.ts
- src/zcash/ZcashEngine.ts
- src/zcash/zcashTypes.ts
- yarn.lock
---
- https://app.asana.com/0/0/1206925152552727
> Zcash - Add Orchard pool and ZIP-317 support

- CHANGELOG.md
- src/ethereum/networkAdapters/EvmScanAdapter.ts
- test/ethereum/network/evmScanTxMerging.test.ts
none
none
---
- https://app.asana.com/0/0/1207126281144803
> Merge regular and internal EvmScanAdapter transaction queries

- CHANGELOG.md
- src/tezos/tezosInfo.ts
- src/zcash/zcashInfo.ts
none
Update Zcash and Tezos nodes.
---
- https://app.asana.com/0/0/1207262641546810
> Node updates

- CHANGELOG.md
- src/polkadot/PolkadotEngine.ts
---
- https://app.asana.com/0/0/1205615584415984
> Show failed Polkadot transactions that were charged a fee

- CHANGELOG.md
- src/algorand/AlgorandEngine.ts
- src/cosmos/CosmosEngine.ts
- src/declare-modules.d.ts
- src/ethereum/info/ethereumclassicInfo.ts
- src/ethereum/info/goerliInfo.ts
- src/ethereum/info/kovanInfo.ts
- src/ethereum/info/rinkebyInfo.ts
- src/ethereum/info/ropstenInfo.ts
- src/ripple/RippleEngine.ts
- src/solana/SolanaEngine.ts
- src/tron/TronEngine.ts
- src/tron/tronInfo.ts
- src/tron/tronTypes.ts
---
- https://app.asana.com/0/0/1206096604395365
> Algorand, Cosmos, Solana, XRP, and Tron - Add bulk balance fetching and onNewTokens callback 

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
- src/ethereum/ethereumTypes.ts
- src/ethereum/fees/ethMiningFees.ts
- src/ethereum/info/ethereumInfo.ts
---
- https://app.asana.com/0/0/1200217514018031
> (EVM tokens) Add ability to override eth_estimateGas results with hardcoded limit

- CHANGELOG.md
- src/algorand/AlgorandEngine.ts
- src/ethereum/EthereumEngine.ts
- src/polkadot/PolkadotEngine.ts
---
- https://app.asana.com/0/0/1207326790089386
> Fix ALGO balance lookup for token transactions

- CHANGELOG.md
- src/ethereum/networkAdapters/EvmScanAdapter.ts
- test/ethereum/network/evmScanTxMerging.test.ts
none
none
---
- https://app.asana.com/0/0/1207361376123586
> Fix mismatching networkFee assertion for mergeEdgeTransactions

- CHANGELOG.md
- src/ethereum/info/zksyncInfo.ts
none
none
---
- https://app.asana.com/0/0/1207361783628977
> Add more evmscan servers to zkSync

- CHANGELOG.md
- src/cosmos/info/thorchainruneInfo.ts
none
none
---
- https://app.asana.com/0/0/1207355978231281
> Remove Thorchain synth assets

- CHANGELOG.md
- src/piratechain/PiratechainEngine.ts
- src/piratechain/piratechainTypes.ts
- src/zcash/ZcashEngine.ts
- src/zcash/zcashTypes.ts
---
- https://app.asana.com/0/0/1205711770788619
> Cache Zcash and Piratechain addresses locally

- CHANGELOG.md
- src/cosmos/CosmosEngine.ts
- src/cosmos/cosmosUtils.ts
none
none
---
- https://app.asana.com/0/0/1207460908169492
> Add Cosmos ADR36 support

- src/cosmos/CosmosEngine.ts
- src/cosmos/cosmosTypes.ts
- src/cosmos/cosmosUtils.ts
---
- https://app.asana.com/0/0/1207361376123590
> Rework Cosmos transaction query

- src/ethereum/ethereumInfos.ts
- src/ethereum/info/mumbaiInfo.ts
- src/fio/fioInfo.ts
- test/eos/activation.test.ts
---
- https://app.asana.com/0/0/1207474088337605
> Add 'mumbai' plugin (MATIC testnet)

- CHANGELOG.md
- package.json
- src/piratechain/PiratechainEngine.ts
- src/piratechain/PiratechainTools.ts
- src/piratechain/piratechainInfo.ts
- src/piratechain/piratechainTypes.ts
- src/zcash/ZcashTools.ts
- src/zcash/zcashInfo.ts
- src/zcash/zcashTypes.ts
- yarn.lock
none
none
---
- https://app.asana.com/0/0/1207485024420879
> Allow Piratechain `derivePublicKey` to fail in case native code is missing

- CHANGELOG.md
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/info/zksyncInfo.ts
- src/solana/solanaInfo.ts
---
- https://app.asana.com/0/0/1207604270480102
> Add BOBBY and ZK

- CHANGELOG.md
- src/ethereum/info/ethereumInfo.ts
none
none
---
- https://app.asana.com/0/0/1205578166226699
> Add Liberland Dollar and Merit tokens

- CHANGELOG.md
- src/common/types.ts
- src/solana/SolanaEngine.ts
- src/solana/solanaTypes.ts
none
none
---
- https://app.asana.com/0/0/1207570211348323
> Solana: Allow unsignedTx passthrough to makeSpend

- src/piratechain/PiratechainTools.ts
- src/piratechain/piratechainTypes.ts
---
- https://app.asana.com/0/0/1207635550315596
> Pirate: Use fallback public key for cases where sdk isn't present

- src/algorand/AlgorandEngine.ts
- src/binance/BinanceEngine.ts
- src/cardano/CardanoEngine.ts
- src/common/network.ts
- src/cosmos/CosmosEngine.ts
- src/eos/EosEngine.ts
- src/ethereum/EthereumNetwork.ts
- src/filecoin/FilecoinEngine.ts
- src/fio/FioEngine.ts
- src/hedera/HederaEngine.ts
- src/piratechain/PiratechainEngine.ts
- src/polkadot/PolkadotEngine.ts
- src/ripple/RippleEngine.ts
- src/solana/SolanaEngine.ts
- src/stellar/StellarEngine.ts
- src/tezos/TezosEngine.ts
- src/tron/TronEngine.ts
none
none
---
- https://app.asana.com/0/0/1207721444734363
> Reduce polling

- CHANGELOG.md
- src/common/smartPay.ts
- src/common/types.ts
none
none
---
- https://app.asana.com/0/0/1207798173045485
> Use asNumberString type for asSmartPayQrDecode to fix QR decoding

- CHANGELOG.md
- src/fio/FioEngine.ts
Per a known bug on their chain, this is a temporary workaround.
none
none
---
- https://app.asana.com/0/0/1207730139556448
> Temporarily omit FIO tpid

- CHANGELOG.md
- package.json
- src/binance/BinanceEngine.ts
- src/common/CurrencyEngine.ts
- src/common/periodicTask.ts
- src/common/utils.ts
- src/ethereum/EthereumEngine.ts
- src/ethereum/EthereumNetwork.ts
- src/ethereum/EthereumTools.ts
- src/ethereum/ethereumTypes.ts
- src/ethereum/fees/feeProviders.ts
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/networkAdapters/AmberdataAdapter.ts
- src/ethereum/networkAdapters/BlockbookAdapter.ts
- src/ethereum/networkAdapters/BlockbookWsAdapter.ts
- src/ethereum/networkAdapters/BlockchairAdapter.ts
- src/ethereum/networkAdapters/BlockcypherAdapter.ts
- src/ethereum/networkAdapters/EvmScanAdapter.ts
- src/ethereum/networkAdapters/FilfoxAdapter.ts
- src/ethereum/networkAdapters/PulsechainScanAdapter.ts
- src/ethereum/networkAdapters/RpcAdapter.ts
- src/ethereum/networkAdapters/types.ts
- src/zcash/ZcashEngine.ts
- test/ethereum/network/evmScanTxProcessing.test.ts
- yarn.lock
none
none
---
- https://app.asana.com/0/0/1207721444734368
> Integrate BlockbooWsAdapter with push-based WebSocket syndication

- CHANGELOG.md
- src/common/CurrencyEngine.ts
none
none
---
- https://app.asana.com/0/0/1207662493389289
> Prevent fatal error reporting for missing txlist json file

- CHANGELOG.md
- src/tron/TronTools.ts
none
none
---
- https://app.asana.com/0/0/1207707000925502
> Special case the `usdt-trc20` uri prefix

- CHANGELOG.md
- src/zcash/ZcashEngine.ts
none
none
---
- https://app.asana.com/0/0/1207269419160387
> Use additional insufficient funds check before sending amount to synchronizer

- CHANGELOG.md
- src/fio/FioEngine.ts
---
- https://app.asana.com/0/0/1207873405885398
> Fix FIO names updates

- CHANGELOG.md
- src/ethereum/info/holeskyInfo.ts
none
none
---
- https://app.asana.com/0/0/1207900893886722
> Fix Holesky testnet params

- package.json
- src/declare-modules.d.ts
- src/solana/SolanaEngine.ts
- src/solana/SolanaTools.ts
- src/solana/solanaTypes.ts
---
- https://app.asana.com/0/0/1207893029863870
> Solana - Add base58 private key import

- CHANGELOG.md
- src/ethereum/info/ethereumInfo.ts
none
none
---
- https://app.asana.com/0/0/1207925799912551
> Fix incorrect protocol for blockbook-ws connection URLs

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
- src/ethereum/ethereumTypes.ts
- src/ethereum/info/zksyncInfo.ts
none
none
---
- https://app.asana.com/0/0/1207994890600882
> zkSync - Update USDCs

- CHANGELOG.md
- src/solana/solanaInfo.ts
none
none
---
- https://app.asana.com/0/0/1207944980300142
> Add new Solana tokens

- src/solana/solanaInfo.ts
---
- https://app.asana.com/0/0/1208067229566508
> Fix wrapped SOL currency code

- CHANGELOG.md
- src/ethereum/ethereumTypes.ts
- src/ethereum/info/amoyInfo.ts
- src/ethereum/info/arbitrumInfo.ts
- src/ethereum/info/avalancheInfo.ts
- src/ethereum/info/baseInfo.ts
- src/ethereum/info/binancesmartchainInfo.ts
- src/ethereum/info/celoInfo.ts
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/info/fantomInfo.ts
- src/ethereum/info/filecoinFevmCalibrationInfo.ts
- src/ethereum/info/filecoinFevmInfo.ts
- src/ethereum/info/holeskyInfo.ts
- src/ethereum/info/optimismInfo.ts
- src/ethereum/info/polygonInfo.ts
- src/ethereum/info/rskInfo.ts
- src/ethereum/info/sepoliaInfo.ts
- src/ethereum/info/zksyncInfo.ts
none
none
---
- https://app.asana.com/0/0/1207103038745538
> Add dRPC nodes to EVM chains

- CHANGELOG.md
- src/ethereum/networkAdapters/EvmScanAdapter.ts
none
none
---
- https://app.asana.com/0/0/1207882588906997
> Add evmscan fallback for eth_getTransactionReceipt in getL1RollupFee

- CHANGELOG.md
- src/ethereum/info/ethereumInfo.ts
none
none
---
- https://app.asana.com/0/0/1208127979050032
> Rename COMBO to Furucombo

- CHANGELOG.md
- src/solana/SolanaTools.ts
none
none
---
- https://app.asana.com/0/0/1207994567051207
> Fix getTokenId to validate token address

- CHANGELOG.md
- src/cardano/CardanoEngine.ts
- src/cardano/CardanoTools.ts
- src/cardano/asStakingTx.ts
- src/cardano/cardanoTypes.ts
- src/common/trial.ts
- test/fio/cardanoTxProcessing.test.ts
In addition to the changes needed for Cardano staking, there is a private key optimization included in this PR to improve signing performance.
none
none
---
- https://app.asana.com/0/0/1207289569255345
> Cardano Staking Infra

- src/fio/FioEngine.ts
---
- https://app.asana.com/0/0/1208249602405342
> Fix parseAction throw on null action name

- CHANGELOG.md
- src/cardano/CardanoEngine.ts
none
none
---
- https://app.asana.com/0/0/1208229808315265
> Fix ADA staking metadata

- CHANGELOG.md
- package.json
- src/react-native.ts
- src/zcash/ZcashEngine.ts
- src/zcash/zcashTypes.ts
- yarn.lock
https://github.com/EdgeApp/react-native-zcash/pull/57
none
---
- https://app.asana.com/0/0/1208356966046118
> Replace sendToAddress with CreateTransfer

- CHANGELOG.md
- src/piratechain/PiratechainEngine.ts
none
none
---
- https://app.asana.com/0/0/1208413268237721
> Remove synchronizer bumping

- CHANGELOG.md
- src/algorand/AlgorandEngine.ts
- src/ripple/RippleEngine.ts
none
none
---
- https://app.asana.com/0/0/1208174615268143
> Immediately check for unactivated tokens after changeEnabledTokenIds

- CHANGELOG.md
- src/common/CurrencyEngine.ts
none
none
---
- https://app.asana.com/0/0/1208393510888981
> Increase MAX_TRANSACTIONSto 2500

- CHANGELOG.md
- src/piratechain/PiratechainEngine.ts
- src/zcash/ZcashEngine.ts
none
none
---
- https://app.asana.com/0/0/1208287065968694
> Await synchronizer initialization in public methods instead of throwing `synchronizer undefined`error

- CHANGELOG.md
- src/polkadot/PolkadotTools.ts
none
none
---
- https://app.asana.com/0/0/1208561731583340
> Disable DOT sends to 0x addresses

- CHANGELOG.md
- src/ethereum/EthereumNetwork.ts
none
none
---
- https://app.asana.com/0/0/1208732408875868
> Increase needsLoop interval to fix performance regression___

- CHANGELOG.md
- src/fio/FioEngine.ts
none
none
---
- https://app.asana.com/0/0/1208401446731950
> Fix unstakefio amount in stakedAmounts

- CHANGELOG.md
- src/ethereum/EthereumNetwork.ts
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/networkAdapters/BlockbookWsAdapter.ts
- src/ethereum/networkAdapters/types.ts
none
none
---
- https://app.asana.com/0/0/1208525574472617
> Fix EVM websocket polling

- CHANGELOG.md
- src/polkadot/PolkadotEngine.ts
- src/polkadot/info/liberlandInfo.ts
- src/polkadot/info/liberlandTestnetInfo.ts
- src/polkadot/info/polkadotInfo.ts
- src/polkadot/polkadotTypes.ts
- test/processLiberlandTransaction.test.ts
none
none
---
- https://app.asana.com/0/0/1207238792534941
> Implement LLD tx history

- CHANGELOG.md
- src/ethereum/EthereumNetwork.ts
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/networkAdapters/BlockbookWsAdapter.ts
- src/ethereum/networkAdapters/types.ts
redo of https://github.com/EdgeApp/edge-currency-accountbased/pull/854
none
none
---
- https://app.asana.com/0/0/1208525574472617
> REDO: Sam/ws polling

- src/zcash/ZcashEngine.ts
- src/zcash/zcashTypes.ts
https://github.com/EdgeApp/edge-core-js/pull/626
none
---
- https://app.asana.com/0/0/1208490257069899
> Add getAddresses method

- CHANGELOG.md
- src/solana/SolanaEngine.ts
- src/solana/SolanaTools.ts
- src/solana/solanaInfo.ts
- src/solana/solanaTypes.ts
none
none
---
- https://app.asana.com/0/0/1208879100999139
> Solana - use stake-weight RPC for broadcasting transactions

- CHANGELOG.md
- src/ripple/rippleInfo.ts
none
none
---
- https://app.asana.com/0/0/1208888448558667
> Ripple - update base reserves

- CHANGELOG.md
- src/ethereum/info/binancesmartchainInfo.ts
none
none
---
- https://app.asana.com/0/0/1208872009746415
> Fix WBNB denomination name

- CHANGELOG.md
- src/ethereum/EthereumNetwork.ts
none
none
---
- https://app.asana.com/0/0/1208890209482184
> Fix incorrect acquireTokenBalance implementation

- src/algorand/algorandInfo.ts
none
none
---
- https://app.asana.com/0/0/1208794473644970
> Update Algorand explorer config

- CHANGELOG.md
- src/zcash/ZcashEngine.ts
none
none
---
- https://app.asana.com/0/0/1207650232543584
> Don't show negative values when attempting to max send small amounts

- CHANGELOG.md
- src/ripple/RippleEngine.ts
- src/ripple/RippleTools.ts
none
none
---
- https://app.asana.com/0/0/1207992885954422
> Check recipient trust lines before sending token

- CHANGELOG.md
- src/ethereum/EthereumTools.ts
none
none
---
- https://app.asana.com/0/0/1208720281205766
> Fix `parseUri` builtin token matching

- CHANGELOG.md
- src/tron/TronEngine.ts
none
none
---
- https://app.asana.com/0/0/1208949347458608
> (Tron) Integrate dynamic `energy_factor` fee

- CHANGELOG.md
- src/ethereum/info/pulsechainInfo.ts
none
none
---
- https://app.asana.com/0/0/1208795574366279
> Fix broken address and transaction explorer links

- CHANGELOG.md
- src/cosmos/engine/ThorchainEngine.ts
none
none
---
- https://app.asana.com/0/0/1209005434171572
> WIP set rune gaslimit and fee

- CHANGELOG.md
- src/cosmos/engine/CosmosEngine.ts
- src/cosmos/engine/ThorchainEngine.ts
none
none
---
- https://app.asana.com/0/0/1209130472409649
> Rune fee display

- CHANGELOG.md
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/info/holeskyInfo.ts
none
none
---
- https://app.asana.com/0/0/1209128130334518
> Fix alchemy url

- CHANGELOG.md
- src/fio/FioEngine.ts
- src/fio/fioTypes.ts
none
none
---
- https://app.asana.com/0/0/1208711103056196
> Fix FIO obt data encryption/decryption

- CHANGELOG.md
- src/common/utils.ts
- src/solana/SolanaEngine.ts
- src/solana/SolanaTools.ts
- src/solana/solanaInfo.ts
- src/solana/solanaTypes.ts
none
none
---
- https://app.asana.com/0/0/1209199800706689
> Solana query cleanups

- CHANGELOG.md
- src/sui/SuiEngine.ts
none
none
---
- https://app.asana.com/0/0/1209217201325551
> Fix Map handling in `processTransaction`

- src/ton/TonEngine.ts
- src/ton/TonTools.ts
- src/ton/tonTypes.ts
none
none
---
- https://app.asana.com/0/0/1209207870668232
> Fix TON transaction handling

- src/solana/SolanaEngine.ts
- src/solana/solanaInfo.ts
- src/solana/solanaTypes.ts
none
none
---
- https://app.asana.com/0/0/1209228669381844
> Add Solana broadcast retry logic

- CHANGELOG.md
- src/polkadot/PolkadotEngine.ts
none
none
---
- https://app.asana.com/0/0/1209152553660791
> Correctly handle token transaction fees in PolkadotEngine

- CHANGELOG.md
- src/solana/SolanaEngine.ts
none
none
---
- https://app.asana.com/0/0/1209060330589965
> Solana - Fix priority fee for undefined networkFeeOption

- CHANGELOG.md
- src/ethereum/info/ethereumInfo.ts
Rename old token symbol and name with "Classic" and "C" and add the new
contract address for the new token.
none
none
---
- https://app.asana.com/0/0/1209264183233601
> Add new USDS token

- CHANGELOG.md
- src/ethereum/ethereumInfos.ts
- src/ethereum/info/abstractInfo.ts
- src/ethereum/info/zksyncInfo.ts
none
none
---
- https://app.asana.com/0/0/1209257679727563
> Add abstract L2 plugin

- CHANGELOG.md
- src/solana/SolanaEngine.ts
none
none
---
- https://app.asana.com/0/0/1209065255458332
> Allow sending to Program Derived Address

- CHANGELOG.md
- src/fio/FioEngine.ts
none
none
---
- https://app.asana.com/0/0/1209468305697583
> Fix FIO broadcast regression

- src/ethereum/info/abstractInfo.ts
---
- https://app.asana.com/0/0/1209491785373393
> Fix Abstract capitalization

- .travis.yml
- CHANGELOG.md
- src/ethereum/ethereumTypes.ts
- src/ethereum/info/abstractInfo.ts
- src/ethereum/networkAdapters/EvmScanAdapter.ts
This is a bandaid so amounts are saved correctly. Abstract transactions produce a lot of internal transactions don't add up accurately in mergeEdgeTransactions.
none
none
---
- https://app.asana.com/0/0/1209527593773378
> Abstract chain - Disable internal transaction query

- package.json
- src/cardano/CardanoEngine.ts
- src/cardano/CardanoTools.ts
- yarn.lock
---
- https://app.asana.com/0/0/1209310455667614
> Upgrade @emurgo/cardano-serialization-lib to 14.1.1

- CHANGELOG.md
- src/algorand/AlgorandEngine.ts
- src/cardano/CardanoEngine.ts
- src/common/CurrencyEngine.ts
- src/cosmos/engine/CosmosEngine.ts
- src/cosmos/engine/ThorchainEngine.ts
- src/eos/EosEngine.ts
- src/filecoin/FilecoinEngine.ts
- src/fio/FioEngine.ts
- src/piratechain/PiratechainEngine.ts
- src/polkadot/PolkadotEngine.ts
- src/ripple/RippleEngine.ts
- src/solana/SolanaEngine.ts
- src/stellar/StellarEngine.ts
- src/sui/SuiEngine.ts
- src/tezos/TezosEngine.ts
- src/ton/TonEngine.ts
- src/tron/TronEngine.ts
- src/zcash/ZcashEngine.ts
none
none
---
- https://app.asana.com/0/0/1209208659072454
> Optimize Solana transaction query

- CHANGELOG.md
- src/algorand/AlgorandEngine.ts
none
none
---
- https://app.asana.com/0/0/1209345494542285
> Add handled broadcast error

- CHANGELOG.md
- src/ethereum/info/fantomInfo.ts
none
none
---
- https://app.asana.com/0/0/1209265630674814
- https://app.asana.com/0/0/1209632805849052
> Update currency info for USDC(FTM)

- CHANGELOG.md
- src/sui/SuiEngine.ts
none
none
---
- https://app.asana.com/0/0/1209589747789500
> Enforce the arbitrary Sui max spend limit

- CHANGELOG.md
- src/solana/SolanaEngine.ts
none
none
---
- https://app.asana.com/0/0/1209673067825474
> Fix SOL amount handling for DEX transactions

- CHANGELOG.md
- src/ethereum/ethereumInfos.ts
- src/ethereum/info/sonicInfo.ts
> Accbased: Add Sonic

- CHANGELOG.md
- src/tron/TronEngine.ts
none
none
---
- https://app.asana.com/0/0/1209863797723969
> Fixed skipping first tx query for most tokens

- CHANGELOG.md
- src/ethereum/fees/feeProviders.ts
- src/ethereum/info/fantomInfo.ts
none
none
---
- https://app.asana.com/0/0/1210014858633908
> Remove ftmscan.com

- src/ethereum/info/avalancheInfo.ts
none
none
---
- https://app.asana.com/0/0/1209647384774119
> AVAX - Add additional etherscan compatible api

- CHANGELOG.md
- src/ethereum/networkAdapters/EvmScanAdapter.ts
none
none
---
- https://app.asana.com/0/0/1210175225647710
> Handle 'No internal transactions found' message from Blockscout servers

- CHANGELOG.md
- src/cosmos/CosmosTools.ts
- src/cosmos/cosmosInfos.ts
- src/cosmos/cosmosRegistry.ts
- src/cosmos/cosmosTypes.ts
- src/cosmos/engine/ThorchainEngine.ts
- src/cosmos/info/thorchainruneInfo.ts
- src/cosmos/info/thorchainruneStagenetInfo.ts
- src/cosmos/thorchainTypes.ts
none
none
---
- https://app.asana.com/0/0/1210063554025852
> Thorchain - Add TCY and testnet

- src/tron/TronEngine.ts
- src/tron/tronTypes.ts
none
none
---
- https://app.asana.com/0/0/1210006356857589
> Update first transaction query

- CHANGELOG.md
- src/tron/TronEngine.ts
- src/tron/tronTypes.ts
- src/tron/tronUtils.ts
none
none
---
- https://app.asana.com/0/0/1210200706894239
> Revert Tron tx query optimizations

- CHANGELOG.md
- src/ethereum/ethereumTypes.ts
- src/ethereum/fees/feeProviders.ts
- src/ethereum/info/arbitrumInfo.ts
- src/ethereum/info/avalancheInfo.ts
- src/ethereum/info/baseInfo.ts
- src/ethereum/info/binancesmartchainInfo.ts
- src/ethereum/info/celoInfo.ts
- src/ethereum/info/ethereumInfo.ts
- src/ethereum/info/optimismInfo.ts
- src/ethereum/info/polygonInfo.ts
- src/ethereum/info/sonicInfo.ts
- src/ethereum/info/zksyncInfo.ts
- src/ethereum/networkAdapters/EvmScanAdapter.ts
**Only for supported networks:**
Ethereum Mainnet (Chain ID: 1)
Optimism (Chain ID: 10)
Polygon (Chain ID: 137)
Sonic (Chain ID: 146)
Binance Smart Chain (Chain ID: 56)
Base (Chain ID: 8453)
Avalanche C-Chain (Chain ID: 43114)
Arbitrum One (Chain ID: 42161)
Celo (Chain ID: 42220)
zkSync Era (Chain ID: 324)
**Unsupported:**
RSK (Chain ID: 30)
PulseChain (Chain ID: 369)
Fantom (Chain ID: 250)
BOB (Chain ID: 60808)
EthereumPOW (Chain ID: 10001)
Ethereum Classic (Chain ID: 61)
none
none
---
- https://app.asana.com/0/0/1210119927809223
> Upgrade to Etherscan V2

- src/stellar/stellarInfo.ts
- src/zano/zanoInfo.ts
none
none
---
- https://app.asana.com/0/0/1210221283659013
> Update Zano and Stellar memos

- CHANGELOG.md
- src/common/innerPlugin.ts
- src/zano/zanoInfo.ts
- src/zano/zanoTypes.ts
none
none
---
- https://app.asana.com/0/0/1210145057911896
> Add Zano tokens from info server

- CHANGELOG.md
- src/cosmos/engine/CosmosEngine.ts
none
none
---
- https://app.asana.com/0/0/1210336219030714
> Fill in MakeTxDeposit Edge transaction data when sending one asset

- CHANGELOG.md
- src/algorand/AlgorandEngine.ts
- src/cardano/CardanoEngine.ts
- src/common/CurrencyEngine.ts
- src/cosmos/engine/CosmosEngine.ts
- src/cosmos/engine/ThorchainEngine.ts
- src/eos/EosEngine.ts
- src/ethereum/EthereumNetwork.ts
- src/ethereum/networkAdapters/FilfoxAdapter.ts
- src/filecoin/FilecoinEngine.ts
- src/fio/FioEngine.ts
- src/hedera/HederaEngine.ts
- src/piratechain/PiratechainEngine.ts
- src/polkadot/PolkadotEngine.ts
- src/ripple/RippleEngine.ts
- src/solana/SolanaEngine.ts
- src/stellar/StellarEngine.ts
- src/sui/SuiEngine.ts
- src/tezos/TezosEngine.ts
- src/ton/TonEngine.ts
- src/tron/TronEngine.ts
- src/zano/ZanoEngine.ts
- src/zcash/ZcashEngine.ts
none
none
---
- https://app.asana.com/0/0/1209794874358734
> New-tx safety

- src/ethereum/ethereumConsts.ts
- src/ethereum/fees/feeProviders.ts
none
none
---
- https://app.asana.com/0/0/1210443636678496
> Remove gas station multiplier

- CHANGELOG.md
- src/common/CurrencyEngine.ts
- src/ethereum/EthereumEngine.ts
- src/ethereum/ethereumTypes.ts
- src/ethereum/networkAdapters/EvmScanAdapter.ts
- src/ethereum/networkAdapters/PulsechainScanAdapter.ts
- test/ethereum/network/evmScanTxProcessing.test.ts
none
none
---
- https://app.asana.com/0/0/1210346829771659
- https://app.asana.com/0/0/1210515530676589
> Prevent `makeSpend` when pending transactions exist

- CHANGELOG.md
- src/zano/ZanoEngine.ts
- src/zano/zanoTypes.ts
none
none
---
- https://app.asana.com/0/0/1205615584416053
> Add resolveName otherMethod for Zano aliases

- CHANGELOG.md
- src/zano/ZanoTools.ts
none
none
---
- https://app.asana.com/0/0/1210714826812044
> Validate deep-link currencyCode against requested currencyCode

- CHANGELOG.md
- src/zano/ZanoTools.ts
none
none
---
- https://app.asana.com/0/0/1210833092832346
> Do not assume deeplink comment is a `uniqueIdentifier`

- CHANGELOG.md
- src/ethereum/info/botanixInfo.ts
none
none
---
- https://app.asana.com/0/0/1210868690320244
> Fix Botanix displayName

- CHANGELOG.md
- src/ethereum/EthereumEngine.ts
To allow transactions with pending transactions when explicitly requested
https://github.com/EdgeApp/edge-core-js/pull/673
none
---
- https://app.asana.com/0/0/1210816418379145
> `allowChainedPending` support in EthereumEngine

- CHANGELOG.md
- src/ethereum/info/botanixInfo.ts
> Fix Botanix assetDisplayName

- CHANGELOG.md
- package.json
- src/common/types.ts
- src/zano/ZanoEngine.ts
- src/zano/zanoTypes.ts
- yarn.lock
https://github.com/EdgeApp/react-native-zano/pull/7
none
---
- https://app.asana.com/0/0/1211255931597794
> Zano - add burn asset support

- package.json
- src/zano/zanoTypes.ts
- yarn.lock
https://github.com/EdgeApp/react-native-zano/pull/8
none
---
- https://app.asana.com/0/0/1211349015797711
> Fix  to match new rnzano type
