src/common/types.js

Checking against "string" causes the constructor to never load the query height and so it always initializes to 0 and we end up querying all transactions on login

Change lastAddressQueryHeight type check to 'number'

---

src/eos/eosEngine.js
src/stellar/stellarEngine.js

Fixes swap error when multiple makeSpends are called but anything other than the latest one is used for signTx/broadcastTx

Hold more than one pending transaction for XLM

---

src/common/engine.js

Only update a transaction if the blockHeight increases or is the same and date, amount, or fee changes

Fix fluttering ETH confirmation status

---

src/common/utils.js

Don't use big number library for conversion but native Buffer library instead

Fix hexToBuf to properly handle keys with leading zeros

---

src/common/utils.js
src/ethereum/ethEngine.js
src/ethereum/ethInfo.js

Utilize multiple ether APIs for blockchain queries
Fixes stuck loading of ether wallets due to rate limiting from APIs. This PR adds use of Blockscout and Infura in addition to etherscan

Multicast ether APIs

---

src/ethereum/ethEngine.js

The purpose of this task is to get the Ethereum plugin to throw an error (insufficient funds) when there is not enough of a token balance to cover the transaction amount.
Asana Task: https://app.asana.com/0/361770107085503/1113213741273785/f

Implement fix for insufficient token balance causing error

---

src/common/engine.js
src/common/types.js
src/eos/eosEngine.js
src/ethereum/ethEngine.js
src/stellar/stellarEngine.js
src/xrp/xrpEngine.js
test/engine/engine.test.js
test/engine/engine.txs.js

* Mark dropped transactions with blockHeight = -1 and nativeAmount = '0'
* Sanitize transaction queries to ensure blockheights from APIs are non-negative
* Add tests for addTransaction to test txidMap, txidList, and transactionList
* Check for dropped transactions when network blockheight changes but no more than once per day

Add ability to detect and mark dropped transactions

---

src/ethereum/ethEngine.js

Put in check for otherParams before attempting to assign to data property (prevents 'property of undefined' error)

Fix missing otherParams.data bug

---

src/ethereum/ethEngine.js
src/rsk/rskEngine.js

The core only understands `InsufficientFundsError`, so this weird error type is causing bad swap experiences for customers.

Remove `ErrorInsufficientFundsMoreEth`

---

src/binance/bnbEngine.js

The API endpoint for checking a balance for an account with no previous transactions causes a `404` error which gets caught, and inside of that catch clause we update the balance as `0` if the wallet literally has zero transactions (you can't have a balance without having transactions).

Fix stuck BNB account balance progress bug

---

package.json
src/xrp/xrpPlugin.js
yarn.lock

This requires Node v10, and won't work with v12 or v11 unless you pass `--ignore-engines` to `yarn`. I have filed https://github.com/ripple/ripple-binary-codec/pull/33 to fix this, so maybe we wait for that to go in before we merge this?

Upgrade to upstream Ripple libraries

---

src/ethereum/ethEngine.js

Allow for a custom nonce to be used when signing account-based transactions. This is useful for when you want to sign a transaction that you expect to broadcast at a later time or via a method other than the Edge Wallet API.

Use nonce parameter if its passed in EdgeTransaction for signing

---

src/ethereum/ethEngine.js
src/ethereum/ethTypes.js

* Modifies `ethEngine.js`
* Adds support for new `rbfTxid` field in `EdgeSpendInfo` in `makeSpend`
* Adds new `nonceUsed` for `EthereumTxOtherParams`
* `makeSpend` uses replaced transaction's fee and nonce
* Saves `nonceUsed` in the `otherParams` field for an ETH `EdgeTransaction`

RBF support for ETH, RSK, and ETH tokens

---

src/ethereum/ethEngine.js

This PR also includes a small bug fix on line 427 when evaluating the getCode response. All spends, regardless of getCode value, were going into the estimateGas path because parseInt was returning NaN and biggystring evaluates NaN as greater than 0.

Overestimate all spends to contracts

---

src/ethereum/ethEngine.js

This fixes accelerating ETH token transactions.

Fix: Use correct currencyCode for tx lookup in ethEngine saveTx

---

src/pluginError.js
src/xrp/xrpEngine.js
src/xrp/xrpInfo.js

NOTE: should merge with https://github.com/EdgeApp/edge-react-gui/pull/2541
Sidenote: Will be better if there is a way to export the `UniqueIdentifierExceedsLengthError` like in the edge-core-js

Added error when XRP destination tag exceed 9 characters

---

src/xrp/xrpEngine.js
src/xrp/xrpSchema.js

This PR addresses two issues. First is to remove the unused "type" value from the transaction schema which was throwing when the SDK returned null for an unrecognized tx type (like delete account). 
The other is to pass the recommended fee to preparePayment in the "instructions" object. preparePayment calls getFee which can fail depending on the type of server, reporting or p2p, the SDK is connected to. https://github.com/ripple/rippled/issues/3812#issuecomment-816871100

Set fee in preparePayment instructions and remove unused type from transaction schema

---

src/xrp/xrpPlugin.js

This solves a user-reported issue with importing XPR keys. Turns out, the XRP library already does all the validation we need.

Remove bogus length checks from the XRP key import

---

src/ethereum/ethPlugin.js
test/plugin/fixtures.js
test/plugin/plugin.test.js

Checking that the currencyCode matches the parent currency for regular
address sends is not necessary and clearly causes an issue with token
sends using an address only (no URI scheme).

Fix regression caused by EIP-681 parseUri implementation

---

src/fio/fioEngine.js

This also resolves an off-by-one error when using slice

Always return results with the newest request first.

---

src/ethereum/ethEngine.js
src/ethereum/maticInfo.js

The values returned by the polygongasstation are good, however, since the code was written for ethgasstation's values which are inflated 10x we need to multiply the already good values by 10.
---
- https://app.asana.com/0/0/1201575938973720

Fix MATIC gas prices

---

src/ethereum/ethEngine.js

For Rarible or other dApps that call the old signTypedData method out of spec,
make a fallback call to see if they meant to use the newest signTypedData_v4.
Created NFT with 'edgeqa' wallet: https://rarible.com/token/0xc9154424B823b10579895cCBE442d41b9Abd96Ed:38190754646147306018708889713384028227784092577956748593609608676919981637636?tab=details
---
- https://app.asana.com/0/0/1201531572537963

Add a Failsafe Call to signTypedData_v4

---

src/common/engine.js
src/ethereum/avaxInfo.js
src/ethereum/ethInfo.js
src/ethereum/ftminfo.js
src/ethereum/maticInfo.js

In addition to adding new default tokens to AVAX, FTM, and MATIC, this PR includes a fix to add a zero balance for newly enabled tokens. This keeps the balances in sync with the enabled tokens list. 
While it's logical to do that, the motivation to do that is it's the simpler solution for edge-react-gui not showing an exchange rate for newly enabled tokens since edge-core-js uses the balances object to build the exchange rates reqeust.
---
- https://app.asana.com/0/0/1201724097897066

Add new tokens

---

src/ethereum/ftminfo.js

https://app.asana.com/0/1190492602001461/1201868425294797/f
FTM RPC servers have been under increasingly heavy load, sometimes completely unresponsive. Add all known RPC servers:
'https://ftmrpc.ultimatenodes.io/',
'https://rpcapi.fantom.network/',
'https://rpc.fantom.network/',
'https://rpc2.fantom.network/',
'https://rpc3.fantom.network/',
'https://rpc.ftm.tools/'

Add new RPC servers for FTM

---

src/ethereum/ethNetwork.js
src/ethereum/ethTypes.js

Internal transactions are by definition between contracts and don't affect the end balance of an EVM account. These queries were overwriting regular transactions with the same txid causing incorrect transaction amounts.

Remove queries for internal transactions

---

src/ethereum/ethEngine.js
src/ethereum/ethNetwork.js

Fetches gas related variables to build the `feeRateUsed` object for GUI
display purpose.
Note that the `gasUsed` has no corresponding key string in the GUI 
repo. We might need to open a task for creating localized strings for
`gasUsed`.
---
- https://app.asana.com/0/0/1200984756686295

Build feeRateUsed for Ethereum receiving txns

---

src/ethereum/ethEngine.js

Allow empty string memo and set as undefined.
Fixes invalid hex value error since empty string is not valid hex
---
- https://app.asana.com/0/0/1202935772126439

Fix spend with empty memo

---

src/stellar/stellarEngine.ts
src/stellar/stellarTypes.ts

Transactions sent with the base fee can fail if the network fees surge. This change makes the engine periodically query the average fees from the 5 most recent ledgers. I chose 50th percentile for low to avoid the case where a transaction fails. Low fees on the stellar network don't mean slower confirmation and instead result in completely failed transactions instead if they don't confirm within a few ledgers.
---
- https://app.asana.com/0/0/1203059815007345

Add dynamic fee to Stellar

---

src/ethereum/info/ethInfo.ts

Old token is no longer used anywhere so we need to change the currency code so its untradeable. 
---
- https://app.asana.com/0/0/1203144923997226

Add new KNC token and rename old one

---

src/ethereum/info/maticInfo.ts

Changelog:
-Update default Polygon BUSD address from Paxos (0xdab529f40e671a1d4bf91361c21bf9f0c9712ab7) to Binance (0x9c9e5fd8bbc25984b178fdce6117defa39d2db39)
---
- https://app.asana.com/0/0/1203555637785705

Update BUSD address from Paxos to Binance

---

src/eos/eosEngine.ts
src/eos/eosTypes.ts

This doesn't fix the staking problems Edge-created wallets run into, but at least we don't crash while sending.
---
- https://app.asana.com/0/0/1203614386381943

Fix EOS crash

---

src/hedera/hederaEngine.ts
src/hedera/hederaTypes.ts

The account balance query isn't working and there isn't any context provided on the error. The error thrown is simply "Error". I couldn't find any relevant information about an outage so this seemed like a logical solution.
---
- https://app.asana.com/0/0/1203696901426654

Hedera: replace client balance query with mirror node

---

src/ethereum/ethEngine.ts

The change didn't account for the sliding standard fee scale. The initial transaction would get the low end and the eventual "max" would scale up the fee. As long as the fee can change with the amount we'll need to use recursion.
---
- https://app.asana.com/0/0/1203782042333694

EVM: Revert getMaxSpendable simplification

---

src/xrp/xrpEngine.ts

Check both DeliveredAmount and delivered_amount is transaction meta object
---
- https://app.asana.com/0/0/1203962644159309

Fix missing XRP token transactions

---

src/common/engine.ts
src/common/tokenHelpers.ts
src/eos/eosPlugin.ts
src/ethereum/ethEngine.ts
src/ethereum/ethPlugin.ts
src/tron/tronPlugin.ts
src/xrp/xrpPlugin.ts

The core requires `getTokenId` to validate its input, as opposed to `addCustomToken`.
We also need to loosen up the rules, since even our own builtin tokens would violate them.
---
- https://app.asana.com/0/0/1203482303205169

Move token validation into getTokenId

---

src/ethereum/info/rskInfo.ts

This pull request is to change the display name for RSK to Rootstock.

Rebrand RSK to Rootstock - display name

---

src/.eslintrc.json
src/common/network.ts
src/common/smartPay.ts
src/common/tokenHelpers.ts
src/ethereum/ethNetwork.ts
src/ethereum/fees/feeProviders.ts
src/react-native.ts
src/tron/tronTypes.ts

We need to import edge-core-js/types to avoid pulling in extra stuff we don't need.
none
none
none

Disallow top-level edge-core-js imports

---

src/algorand/AlgorandEngine.ts
src/algorand/AlgorandTools.ts
src/algorand/algorandTypes.ts
src/common/types.ts
src/ethereum/ethEngine.ts
src/ethereum/ethPlugin.ts
src/ethereum/ethTypes.ts

Wallet connect v1 functionality is directly managed by the engines. This PR updates the existing EVM integration to return more generic params (native amount, network fee, and tokenId) first and then adds wallet connect to Algorand. It's largely a copy/paste of the EVM handling with tweaks to handle the unique ALGO call_request response. 
Futher cleanups and optimizations were not attempted because wallet connect v1 is due to sunset at the end of June 2023.
---
- https://app.asana.com/0/0/1204452616785593

Add wallet connect v1 to Algorand

---

src/algorand/AlgorandEngine.ts
src/ethereum/ethEngine.ts

This is to prevent an error being thrown if the dapp called disconnect rather than the user
---
- https://app.asana.com/0/0/1204481145907714

Don't call disconnect on deleted connecters

---

src/ripple/RippleTools.ts

Since this.rippleApi is never null, change connectApi conditional to check if we have any subscribers. 0 subscribers means we had a killEngine on all engines and we need to reconnect the api.
none
none
none
---
- https://app.asana.com/0/0/1204446128537626

Properly reconnect rippleApi

---

package.json
src/algorand/AlgorandEngine.ts
src/algorand/AlgorandTools.ts
src/algorand/algorandTypes.ts
src/common/types.ts
src/ethereum/EthereumEngine.ts
src/ethereum/EthereumTools.ts
src/ethereum/ethereumTypes.ts
yarn.lock

Wallet Connect is no longer handled in these plugins. Instead, a utility function is provided in order to parse a smart contract payload to identify the amounts and token. Otherwise the host app is responsible for managing the connection. 
---
- https://app.asana.com/0/0/1204857257229134

Deprecate wallet connect v1 and add v2

---

src/ethereum/EthereumEngine.ts

- Fixed: Fixed Ethereum broken max-spend for spend info with undefined nativeAmount
none
none
---
- https://app.asana.com/0/0/1204852037419370

Remove error for nativeAmount assertion for getMaxSpendable use case

---

src/ethereum/EthereumEngine.ts

Fixed: Critical bug that is missing data field for native EVM transactions including a memo
none
none
---
- https://app.asana.com/0/0/1204940534353339

Include `data` from `memo` or `otherParams` for native currency spends

---

src/fio/fioConst.ts
src/tron/tronTypes.ts
src/zcash/zcashTypes.ts

This cleaner is shared across engines and therefore the fallback object will be shared
---
- https://app.asana.com/0/0/1205131987503159

Fix asMaybe object fallback values in shared otherData cleaner

---

src/binance/BinanceEngine.ts
src/common/CurrencyEngine.ts
src/common/smartPay.ts
src/common/utils.ts
src/eos/EosEngine.ts
src/eos/EosTools.ts
src/ethereum/EthereumEngine.ts
src/ethereum/EthereumNetwork.ts
src/fio/FioEngine.ts
src/fio/FioTools.ts
src/hedera/HederaEngine.ts
src/hedera/HederaTools.ts
src/polkadot/PolkadotEngine.ts
src/solana/SolanaEngine.ts
src/stellar/StellarEngine.ts
src/tezos/TezosEngine.ts
src/tron/TronEngine.ts

With the exception of when `io.fetchCors` doesn't exist. Then we have no choice.
- changed: Use `EdgeIo.fetchCors` for all requests.
none
none
---
- https://app.asana.com/0/0/1205163504777914

Only use `io.fetchCors`, never `io.fetch`

---

src/ethereum/info/ethereumclassicInfo.ts

- changed: Removed blockscout API server from ETC info (disabling transaction list retrieval)
none
none
---
- https://app.asana.com/0/0/1205339631453865

Remove Blockscout EVM scan API server from Ethereum Classic

---

src/ripple/RippleEngine.ts
src/ripple/rippleTypes.ts

Fixes missing transactions and incorrect tx amounts
fixed: Properly show xrp tx amounts for all tx types
none
none
none
---
- https://app.asana.com/0/0/1205196599470299

Use xrpl getBalanceChanges for processRippleTransaction

---

src/algorand/AlgorandEngine.ts
src/algorand/AlgorandTools.ts
src/binance/BinanceEngine.ts
src/binance/BinanceTools.ts
src/common/CurrencyEngine.ts
src/eos/EosEngine.ts
src/eos/EosTools.ts
src/ethereum/EthereumEngine.ts
src/ethereum/EthereumTools.ts
src/fio/FioEngine.ts
src/fio/FioTools.ts
src/hedera/HederaEngine.ts
src/hedera/HederaTools.ts
src/polkadot/PolkadotEngine.ts
src/polkadot/PolkadotTools.ts
src/ripple/RippleEngine.ts
src/ripple/RippleTools.ts
src/solana/SolanaEngine.ts
src/solana/SolanaTools.ts
src/stellar/StellarEngine.ts
src/stellar/StellarTools.ts
src/tezos/TezosEngine.ts
src/tezos/TezosTools.ts
src/tron/TronEngine.ts
src/tron/TronTools.ts
src/zcash/ZcashEngine.ts
src/zcash/ZcashTools.ts

- changed: Move deprecated display-key methods from the engines to the tools. This requires edge-core-js v0.21.2 or later.
none
Maybe use the "files changed" view, since that will make the review easier. We could even go so far as to squash the two commits together.
However, the second commit is a breaking change, since it means we will no longer be compatible with older core versions.
---
- https://app.asana.com/0/0/1205139579993261

Update display-key methods

---

package.json
src/filecoin/FilecoinEngine.ts
src/filecoin/FilecoinTools.ts
src/filecoin/Filscan.ts
src/filecoin/RpcExtra.ts
src/filecoin/filecoinInfo.ts
src/filecoin/filecoinTypes.ts
src/index.ts
test/plugin/fixtures.ts
test/plugin/plugin.test.ts
yarn.lock

- added: Add Filecoin
none
none
---
- https://app.asana.com/0/0/1204526951399191

Add Filecoin

---

src/index.ts
src/polkadot/PolkadotEngine.ts
src/polkadot/PolkadotTools.ts
src/polkadot/info/liberlandInfo.ts
src/polkadot/info/liberlandTestnetInfo.ts
src/polkadot/info/polkadotInfo.ts
src/polkadot/polkadotInfo.ts
src/polkadot/polkadotTypes.ts

---
- https://app.asana.com/0/0/1205147741891806

Add Liberland

---

src/filecoin/filecoinInfo.ts

- fixed: Use Filscan as the block explorer for Filecoin
none
none
---
- https://app.asana.com/0/0/1205389198015854

Fix Filecoin block explorer

---

src/polkadot/PolkadotEngine.ts
src/polkadot/polkadotTypes.ts

queryMulti is technically more efficient but our usage was causing some inaccurate values to be saved. This can be revisited when more assets are added
---
- https://app.asana.com/0/0/1205428561223918

Simplify polkadot balance queries

---

src/filecoin/FilecoinEngine.ts
src/zcash/ZcashEngine.ts

The date field was missing from the signed transactions so it wasn't being saved (I suppose that's a requirement by the CurrencyEngine implementation). Also, `isSend` had a bug that was copied from `ZcashEngine`; now it's fixed in both places.
- fixed: Bug prevent Filecoin spend trasactions from being saved in the wallet (by `saveTx`)
none
none
---
- https://app.asana.com/0/0/1205428345589472

Fix filecoin spend saving

---

src/filecoin/FilecoinEngine.ts
src/filecoin/Filfox.ts

Heads up. This disables Filscan because I haven't found a convenient way to calculate fees from Filscan's API. I haven't quit wrapped my head around [how Filecoin fees are calculated](https://spec.filecoin.io/systems/filecoin_vm/gas_fee/), so rather than calculating the fee from the message fields, I use a hack to peer into the "transfer" data returned by Filfox.
- fixed: Filecoin network fee query issue
- changed: Use Filfox exclusively for Filecoin transaction querying
none
none
---
- https://app.asana.com/0/0/1205419647873868

Filecoin network query fixes

---

src/tron/tronInfo.ts

There is no specific memo size on this network - as long as the transaction pays its fees, a byte is a byte.
- changed: Remove the maximum memo length on Tron.
none
none
---
- https://app.asana.com/0/0/1205531946960596

Remove the Tron memo length

---

CHANGELOG.md
src/tron/tronInfo.ts

- fixed: Rename Tron memos to "note".
none
none
---
- https://app.asana.com/0/0/1205534353251276

Rename Tron memos to "note"

---

package.json
src/piratechain/piratechainInfo.ts
src/react-native.ts
src/zcash/ZcashEngine.ts
src/zcash/ZcashTools.ts
src/zcash/zcashInfo.ts
src/zcash/zcashTypes.ts
yarn.lock

Upgrade to latest rnzcash and implement spend-before-sync support. Remove transaction and balance polling in favoring of listening to events.
---
- https://app.asana.com/0/0/1205664938290920

Upgrade react-native-zcash

---

CHANGELOG.md
src/stellar/StellarTools.ts
src/stellar/stellarTypes.ts

- added: Support for 12/24-word mnemonic XLM wallet imports
none
none
---
- https://app.asana.com/0/0/1204800868907796

XLM Mnemonic Phrase Support

---

CHANGELOG.md
package.json
src/react-native.ts
src/zcash/ZcashEngine.ts
src/zcash/ZcashTools.ts
src/zcash/zcashInfo.ts
src/zcash/zcashTypes.ts
yarn.lock

- [x ] Yes
https://github.com/EdgeApp/react-native-zcash/pull/42
Add autoshield support. As processor and balance updates come in, the engine will see if it's able to shield available transparent funds. If so, it will hijack the syncNetwork loop to do so. 
There are a handful of sdk issues I had to account for. Missing android memos and recipients on both platforms meant extra code to determine if a transaction was a shielding transaction so it can be tagged correctly.
---
- https://app.asana.com/0/0/1205458575043813

Add autoshield

---

CHANGELOG.md
src/ripple/RippleEngine.ts
src/ripple/rippleTypes.ts

https://github.com/EdgeApp/edge-core-js/pull/567
Parse XRP DEX orders into EdgeTxActions. Supports OfferCreate and OfferCancel type order tx's
---
- https://app.asana.com/0/0/1205412691849558

Implement XRP DEX order parsing -> EdgeTxAction's

---

CHANGELOG.md
src/ripple/RippleEngine.ts

Fix for only the bugged src/dest direction fix.
Partial fill amounts that happen after the initial order tx will require
a future fix and api change.
none
none
---
- https://app.asana.com/0/0/1205787716339747

XRP EdgeTxActionSwap Direction Fix

---

CHANGELOG.md
src/piratechain/PiratechainEngine.ts

On disk data issues can cause syncing loops that are only resolvable by reinstall. This change will allow import key to be an alternative troubleshooting step but at the cost of forcing each wallet to redownload and sync to initialize a synchronizer with a new alias
---
- https://app.asana.com/0/0/1205838825636596

Use walletId for synchronizer alias

---

CHANGELOG.md
src/ethereum/EthereumNetwork.ts

none
none
---
- https://app.asana.com/0/0/1205935097933115

Fix failed sync of evm wallets

---

CHANGELOG.md
src/ethereum/fees/ethMiningFees.ts

This check prevents the maxPriorityFeePerGas from going negative which would error in creating the transaction.
none
none
---
- https://app.asana.com/0/0/1205973322768969

Ensure at least a 2 GWEI 'tip' to miners

---

CHANGELOG.md
src/cosmos/info/coreumInfo.ts

Coreum is standardizing the ticker as COREUM instead of CORE
---
- https://app.asana.com/0/0/1206099991498416

Update Coreum currency code

---

CHANGELOG.md
src/cosmos/CosmosEngine.ts

The fee isn't finalized until confirmation so we need to leave for the fee to change until the transaction is broadcast.

Overestimate Thorchain transaction fee

---

CHANGELOG.md
src/ethereum/EthereumEngine.ts
src/ethereum/fees/feeProviders.ts

We should include the decimal value in our calculation to be more
precise in our conversion from GWEI to WEI. This is important for some
currencies like Fantom which will reject transactions if their fee is
too low which may happen due to rounding down.
none
none
---
- https://app.asana.com/0/0/1206237652275804

Use decimal values from EVM scan fee API

---

CHANGELOG.md
src/ethereum/fees/feeProviders.ts
src/fio/FioEngine.ts
src/fio/fioConst.ts
test/engine/feeProvider.test.ts

This allows the wallet to still get a balance if they are affected by the unstake bug. The balance is necessary so they can take the necessary actions to fix their account's onchain data.
https://fioprotocol.atlassian.net/wiki/spaces/DAO/pages/852688908/2024-02-07+Token+Locking+Issue+on+Unstake
---
- https://app.asana.com/0/0/1206526184999703

Add fallback balance query for unstake funds chain bug

---

src/ethereum/fees/ethMiningFees.ts

The previous method also considered the L2 component which would fail for large contract calls
---
- https://app.asana.com/0/0/1206637133309629

Switch contract method for gas estimation

---

CHANGELOG.md
src/ethereum/EthereumEngine.ts
src/ethereum/EthereumNetwork.ts
src/ethereum/info/pulsechainInfo.ts
src/ethereum/networkAdapters/EvmScanAdapter.ts
src/ethereum/networkAdapters/PulsechainScanAdapter.ts
src/ethereum/networkAdapters/RpcAdapter.ts
src/ethereum/networkAdapters/types.ts

The old API which is evmscan/blockscout compatible was added as a commit after I did the integration even though that commit proceeds the new integration commit. The new API commit is to include all the new API for PLS as a fallback adaptor now. I figured it’s worth merging this integration into the codebase because I spent the time working on it. The new API isn’t as good as the evmscan adaptor because I am unable to figure out how to get the “next page” parameters to match the passed “startBlock” parameter.
none
none
---
- https://app.asana.com/0/0/1206163473998245

Update Pulsechain integrations for fetching transaction

---

CHANGELOG.md
src/piratechain/PiratechainTools.ts
src/zcash/ZcashTools.ts

This is enforced by the sdk. Throwing here prevents the wallet from being created
---
- https://app.asana.com/0/0/1206270926523609

Force Zcash and Piratechain imports to have 24 words

---

CHANGELOG.md
src/polkadot/PolkadotEngine.ts
src/polkadot/PolkadotTools.ts
src/polkadot/info/liberlandInfo.ts
src/polkadot/info/liberlandTestnetInfo.ts
src/polkadot/info/polkadotInfo.ts
src/polkadot/polkadotTypes.ts

Previous encodings do not impact the wallet's ability to get a balance or spend funds. This means new wallets do not need to save the ss58 encoding used at creation.
none
none
---
- https://app.asana.com/0/0/1206701033325513

Add ss58 format

---

CHANGELOG.md
src/ethereum/EthereumEngine.ts
src/ethereum/ethereumTypes.ts

The reason for this caching appears to only be an optimization. This
optimization cannot be used because zkSync's gas estimation changes when
the transaction value parameter changes. Because chains like zkSync may
change the gas estimation based on the parameters, there is no reason to
cache unless all the parameters are the same. However, there is no
UX instance where the estimation call is made with identical parameters
to warrant the optimization.
Instead, anywhere that the caching is needed, whether for optimization
or for correctness, the implementation for the caching should be done
within that routine.
none
none
---
- …

Remove `LastEstimatedGasLimit` caching mechanism

---

src/common/validateMemos.ts
test/utils/validateMemos.test.ts

none
We had reports that `makeSpend` would succeed with "0x" in our memos, but that the transactions would fail on-chain. Well, no, `makeSpend` won't actually allow this situation, at least in the current release.
---
- https://app.asana.com/0/0/1206985639130703

Unit-test the `validateMemos` function

---

CHANGELOG.md
src/polkadot/PolkadotEngine.ts

It looks like this bug slipped in during the edge-core-js v2 upgrade.
The logic used to compare spend info currency code inequality with
engine currency code.
This change is the correct condition for the refactor.
none
none
---
- https://app.asana.com/0/0/1207258762926303

Fix DOT max spending caused by incorrectly checking `spendInfo.tokenId`

---

CHANGELOG.md
src/cosmos/CosmosEngine.ts
src/cosmos/cosmosTypes.ts
src/cosmos/info/cosmoshubInfo.ts

Recent-ish transaction will still be visible but historical will not. Will need replacement.
---
- https://app.asana.com/0/0/1207361376123588
- https://app.asana.com/0/0/1207409592447625

Disable archive node for Cosmos Hub

---

CHANGELOG.md
package.json
src/algorand/AlgorandTools.ts
src/binance/BinanceTools.ts
src/cardano/CardanoTools.ts
src/common/CurrencyEngine.ts
src/common/tokenHelpers.ts
src/common/uriHelpers.ts
src/cosmos/CosmosTools.ts
src/declare-modules.d.ts
src/eos/EosTools.ts
src/ethereum/EthereumEngine.ts
src/ethereum/EthereumNetwork.ts
src/ethereum/EthereumTools.ts
src/filecoin/FilecoinTools.ts
src/fio/FioTools.ts
src/hedera/HederaTools.ts
src/piratechain/PiratechainTools.ts
src/polkadot/PolkadotTools.ts
src/ripple/RippleEngine.ts
src/ripple/RippleTools.ts
src/solana/SolanaEngine.ts
src/solana/SolanaTools.ts
src/stellar/StellarTools.ts
src/tezos/TezosTools.ts
src/tron/TronTools.ts
src/zcash/ZcashTools.ts
yarn.lock

https://github.com/EdgeApp/edge-core-js/pull/599
none
---
- https://app.asana.com/0/0/1207585261612937

Add `lightMode` support to Solana and EVM engines

---

src/ethereum/EthereumEngine.ts
src/ethereum/ethereumTypes.ts

Required for signing Bity orders
https://github.com/EdgeApp/edge-core-js/pull/605
none
---
- https://app.asana.com/0/0/1207822104319102

Support signing non-hex messages

---

CHANGELOG.md
package.json
src/cosmos/CosmosEngine.ts
src/cosmos/CosmosTools.ts
src/cosmos/cosmosTypes.ts
src/cosmos/info/axelarInfo.ts
src/cosmos/info/coreumInfo.ts
src/cosmos/info/cosmoshubInfo.ts
src/cosmos/info/osmosisInfo.ts
src/cosmos/info/thorchainruneInfo.ts
yarn.lock

none
none
---
- https://app.asana.com/0/0/1207925866929800

Cosmos hardfork support

---

CHANGELOG.md
src/ethereum/EthereumEngine.ts
src/ethereum/info/arbitrumInfo.ts

- Enable EIP1559 support, since the L2 chain supports this.
- Priority fees can be much lower.
- Simply add `gasEstimateForL1` to the gas limit, without multiplying by the gas price. This value represents the number of gas units needed to store the compressed transaction bytes, not the total L1 cost in ETH.
- In the max-spend calculation, multiply `gasEstimateForL1` by the chosen L2 gas price, not the L1 gas price. Unlike `makeSpend`, `getMaxSpendable` deals with fee totals rather than separate prices and limits. The l1 gas price is irrelevant to this calculation, since the fee multiplication happens at L2.
none
none
---
- …

Fix Arbitrum fee calculations

---

CHANGELOG.md
src/fio/FioEngine.ts

We need the ability to provide fresh data on demand to the GUI. Previously, refreshing this data was only done in `checkAccountInnerLoop` .
none
none
---
- https://app.asana.com/0/0/1208153057785487

Expose non-cached getters for addresses, names, and domains

---

CHANGELOG.md
src/cosmos/CosmosTools.ts
src/cosmos/cosmosEngines.ts
src/cosmos/cosmosTypes.ts
src/cosmos/engine/CosmosEngine.ts
src/cosmos/engine/ThorchainEngine.ts
src/cosmos/info/thorchainruneInfo.ts
src/cosmos/thorchainTypes.ts

none
none
---
- https://app.asana.com/0/0/1207873073212943

(Thorchain) Replace rpc tx_search with midgard transaction query

---

CHANGELOG.md
package.json
src/piratechain/PiratechainEngine.ts
src/piratechain/piratechainTypes.ts
src/react-native.ts
src/zcash/ZcashEngine.ts
src/zcash/ZcashTools.ts
src/zcash/zcashTypes.ts
yarn.lock

https://github.com/EdgeApp/react-native-piratechain/pull/14
https://github.com/EdgeApp/react-native-zcash/pull/56
none
---
- https://app.asana.com/0/0/1208178889823047

(ZcashPiratechain) Add error listeners

---

CHANGELOG.md
src/algorand/AlgorandEngine.ts
src/common/innerPlugin.ts
src/common/tokenHelpers.ts
src/common/types.ts
src/cosmos/engine/CosmosEngine.ts
src/ethereum/info/amoyInfo.ts
src/ethereum/info/arbitrumInfo.ts
src/ethereum/info/avalancheInfo.ts
src/ethereum/info/baseInfo.ts
src/ethereum/info/binancesmartchainInfo.ts
src/ethereum/info/bobevmInfo.ts
src/ethereum/info/celoInfo.ts
src/ethereum/info/ethDevInfo.ts
src/ethereum/info/ethereumInfo.ts
src/ethereum/info/ethereumclassicInfo.ts
src/ethereum/info/ethereumpowInfo.ts
src/ethereum/info/fantomInfo.ts
src/ethereum/info/filecoinFevmCalibrationInfo.ts
src/ethereum/info/filecoinFevmInfo.ts
src/ethereum/info/holeskyInfo.ts
src/ethereum/info/optimismInfo.ts
src/ethereum/info/polygonInfo.ts
src/ethereum/info/pulsechainInfo.ts
src/ethereum/info/rskInfo.ts
src/ethereum/info/sepoliaInfo.ts
src/ethereum/info/zksyncInfo.ts
src/solana/solanaInfo.ts

none
none
---
- https://app.asana.com/0/0/1207606246115525

Ethereum/Solana: Support additional tokens from info server

---

CHANGELOG.md
src/cardano/CardanoEngine.ts

none
none
---
- https://app.asana.com/0/0/1208229808315273

Update tx_info request to include inputs

---

CHANGELOG.md
src/ethereum/networkAdapters/EvmScanAdapter.ts

none
none
---
- https://app.asana.com/0/0/1208217866090168

Merge duplicate token transaction data from evmscan

---

CHANGELOG.md
src/ethereum/EthereumNetwork.ts

We've introduced a WebSocket network adapter called BlockbookWsAdapter which would register an address subscription in order to get new transactions from the socket. It would then put the txid into a list. The regular fetchTx pulling routine would only continue under the condition that there are txid in this list. When a txid is pulled from the fetchTxs routine and processed, then it is removed from this txid list. This would eventually stop the pulling once all the txs have been processed. This means that the engine isn't re-fetching pending transactions to get the blockheight once it's confirmed.
Include a condition that the transaction must not only be processed, but also confirmed (blockHeight > 0).
none
none
---
- To see the …

Fix ETH requires a resync or log back in to see new transaction

---

CHANGELOG.md
src/fio/FioEngine.ts

none
none
---
- https://app.asana.com/0/0/1208262469170438

Fix FIO amounts in parseAction

---

CHANGELOG.md
src/ethereum/info/ethereumInfo.ts

These are preventing incoming transactions from appearing.
Because these adapters exist in the list, we call `setupAdapterSubscriptions` on them, which prevents the polling loop from checking any addresses.
Unfortunately, the two WebSocket URL's don't actually work, so we never actually subscribe to the addresses on the WebSocket side either.
This means that updates never appear, so the only way to see incoming transactions is to resync and log out.
This is a temporary solution to solve the immediate problem. The long-term solution is to fix the engine to poll for addresses unless there are active, live, working-for-real WebSocket subscriptions.
none
none

Disable 'blockbook-ws' connections

---

src/ethereum/fees/feeProviders.ts
src/ethereum/networkAdapters/RpcAdapter.ts

---
- https://app.asana.com/0/0/1208326136611437

Update MATIC special cases to POL

---

CHANGELOG.md
src/cardano/CardanoEngine.ts

none
none
---
- https://app.asana.com/0/0/1208401832264547

Add redundancy to Cardano queries

---

CHANGELOG.md
src/ethereum/EthereumNetwork.ts
src/ethereum/ethereumTypes.ts
src/ethereum/info/amoyInfo.ts
src/ethereum/info/arbitrumInfo.ts
src/ethereum/info/avalancheInfo.ts
src/ethereum/info/baseInfo.ts
src/ethereum/info/binancesmartchainInfo.ts
src/ethereum/info/bobevmInfo.ts
src/ethereum/info/celoInfo.ts
src/ethereum/info/ethDevInfo.ts
src/ethereum/info/ethereumInfo.ts
src/ethereum/info/ethereumclassicInfo.ts
src/ethereum/info/ethereumpowInfo.ts
src/ethereum/info/fantomInfo.ts
src/ethereum/info/filecoinFevmCalibrationInfo.ts
src/ethereum/info/filecoinFevmInfo.ts
src/ethereum/info/holeskyInfo.ts
src/ethereum/info/optimismInfo.ts
src/ethereum/info/polygonInfo.ts
src/ethereum/info/pulsechainInfo.ts
src/ethereum/info/rskInfo.ts
src/ethereum/info/sepoliaInfo.ts
src/ethereum/info/zksyncInfo.ts

none
none
---
- https://app.asana.com/0/0/1208401387533229

Fix AVAX missing transaction confirmations

---

CHANGELOG.md
src/cardano/CardanoEngine.ts
src/cardano/cardanoTypes.ts

none
none
---
- https://app.asana.com/0/0/1208660680604944

Fix Cardano UTXO and balance bugs

---

CHANGELOG.md
package.json
src/solana/SolanaEngine.ts
src/solana/SolanaTools.ts
yarn.lock

Solana RPC nodes will throw RPC errors instead of throwing HTTP errors
so they'll fail silently and not reach the CORS fallback methods.
none
none
---
- https://app.asana.com/0/0/1208916602572140

Use `fetchCorsForced` for Solana RPC nodes

---

CHANGELOG.md
src/ripple/RippleEngine.ts
src/ripple/rippleTypes.ts

none
none
---
- https://app.asana.com/0/0/1208621746624102

Ripple - Add destination tag processing

---

CHANGELOG.md
src/solana/solanaInfo.ts

The existing archival nodes were failing or too slow to sync. Using
Helius RPC node exclusively allows us to sync transactions quickly.
A future patch would be to fix the issues with the other two archival
nodes. Known issues with `solana.com` node is a rate limiting issue.
The issue with `alchemy.com` seems to be wide spread. The RPC node
seems to be returning responses that are unexpected to the web3 Solana
library. More debugging is needed to get these services back to a
working state.
none
none
---
- https://app.asana.com/0/0/1208992843324853

Use Helius RPC archival node exclusively

---

CHANGELOG.md
src/common/CurrencyEngine.ts

We had a cacth-22 situation, where we needed a valid checkpoint to consider any transaction new, but we wouldn't update the checkpoint until we saw a new transaction.
Besides the catch-22, a fully-syncd wallet generally wouldn't have any activity that could update the checkpoint, leaving it stuck at undefined until a new transaction comes in, in which case that new transaction would never get a notification. Therefore, we need to set up an initial checkpoint at boot if we don't have one. This will be a one-time operation on a single device. After that, new devices will recieve the synced checkpoint.
none
none
---
- …

Fix new transaction notifications

---

src/algorand/AlgorandEngine.ts
src/cardano/CardanoEngine.ts
src/common/CurrencyEngine.ts
src/cosmos/engine/CosmosEngine.ts
src/cosmos/engine/ThorchainEngine.ts
src/eos/EosEngine.ts
src/ethereum/EthereumEngine.ts
src/filecoin/FilecoinEngine.ts
src/fio/FioEngine.ts
src/hedera/HederaEngine.ts
src/piratechain/PiratechainEngine.ts
src/polkadot/PolkadotEngine.ts
src/ripple/RippleEngine.ts
src/solana/SolanaEngine.ts
src/stellar/StellarEngine.ts
src/sui/SuiEngine.ts
src/tezos/TezosEngine.ts
src/ton/TonEngine.ts
src/tron/TronEngine.ts
src/zcash/ZcashEngine.ts

Instead of directly messing with timers, we can use a periodic task to ensure that there is exactly one copy of each task running at once, and automatically start & stop them as the engine toggles on or off.
none
none
---
- https://app.asana.com/0/0/1209488312133556

Use a `PeriodicTask` in `addToLoop`

---

CHANGELOG.md
src/fio/FioTools.ts

FIO now requires api tokens to be set whenever requesting a `buyAddressRequest`
none
none
---
- https://app.asana.com/0/0/1209321700791831

Require `buyAddressRequest` api tokens

---

CHANGELOG.md
src/ripple/RippleEngine.ts
src/ripple/RippleTools.ts

none
none
---
- https://app.asana.com/0/0/1209195851436299

Harden ripple api connectivity

---

CHANGELOG.md
src/declare-modules.d.ts
src/tron/TronEngine.ts
src/tron/tronTypes.ts
src/tron/tronUtils.ts
test/tronwebToUtf8.test.ts

none
none
---
- https://app.asana.com/0/0/1209654951272385

Tron - add note support to tx query

---

CHANGELOG.md
src/cardano/CardanoEngine.ts
src/cardano/cardanoTypes.ts

This is so that decodeStakingTx to communicate whether a transaction is valid by the engine's state.
none
none
---
- https://app.asana.com/0/0/1209775828409824

Add isSpendable to CardanoTxOtherParams

---

.mocharc.json
.nettest.mocharc.json
CHANGELOG.md
package.json
src/common/utils.ts
src/ethereum/EthereumEngine.ts
src/ethereum/EthereumNetwork.ts
src/ethereum/ethereumTypes.ts
src/ethereum/networkAdapters/EvmScanAdapter.ts
src/ethereum/networkAdapters/types.ts
test/engine/engine.test.ts
test/ethereum/network/evmScanTxProcessing.test.ts

none
none
---
- https://app.asana.com/0/0/1209371329306828

Integrate Edge Change Server

---

CHANGELOG.md
src/tron/TronEngine.ts

- Rely purely on `total_energy` or `energy_used` for the energy estimation, depending on `recipientInStorage`
- Update the `recipientInStorage` check to compare against a self spend dryrun.
- Add heuristic specific to USDT per observations in TronLink wallet and onchain transactions.
none
none
---
- https://app.asana.com/0/0/1210177602128615

Update TRX energy calculation logic

---

CHANGELOG.md
package.json
src/zano/ZanoEngine.ts
src/zano/zanoTypes.ts
yarn.lock

https://github.com/EdgeApp/react-native-zano/pull/5
none
---
- https://app.asana.com/0/0/1210210357632652

Zano - Add multi output support

---

CHANGELOG.md
package.json
src/ethereum/EthereumTools.ts
src/zano/ZanoTools.ts
src/zano/zanoTypes.ts
yarn.lock

https://github.com/EdgeApp/edge-core-js/pull/658
none
---
- https://app.asana.com/0/0/1210145057911906

Add `getTokenDetails` to EVM and Zano

---

CHANGELOG.md
src/ethereum/info/hyperEvmInfo.ts

The hyperliquid.xyz explorer only tracks the main network and not the HyperEVM network.
none
none
---
- https://app.asana.com/0/0/1210882648647095

Change HyperEVM block explorer

---

CHANGELOG.md
src/ethereum/networkAdapters/FilfoxAdapter.ts
src/filecoin/Filfox.ts

none
none
---
- https://app.asana.com/0/0/1210574735069961

Fix Filecoin FEVM token sync status handling for enabled tokens
